### ISSUE TITLE
Realm Object Server starts but isn't accessible if the CloudKit cert path is incorrect.

### ISSUE THREAD

**Issue by skwashua** [realm/realm-object-server#176]
## Goals

When enabling CloudKit support in the configuration.yml, the system should report the bad certificate location.

## Expected Results

Either:
A) The service should not start with an error.
B) Checking the configuration via `--check-configuration` should return an error.

## Actual Results

The service started and `--check-configuration` returned "Realm Object Server configuration valid."

## Steps to Reproduce

Change "private_key_path: 'cloudkit_eckey.pem'" to not include the full path.

## Version of Realm and Tooling

- Realm Object Server Version: 1.4.1
- Flavor: Developer
- Server OS & Version: Ubuntu 16.04.2 LTS
- Client SDK Version: N/A
- Client OS & Version: N/A

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    realm-object-server.service - Realm Object Server
   Loaded: loaded (/etc/systemd/system/realm-object-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-04-23 18:52:28 MDT; 2s ago
 Main PID: 7482 (realm-object-se)
   CGroup: /system.slice/realm-object-server.service
           └─7482 /usr/lib/realm-object-server/node/bin/node /usr/bin/realm-object-server -c /etc/realm/configuration.yml
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
Apr 23 16:53:05 link systemd[1]: Started Realm Object Server.
Apr 23 16:53:14 link realm-object-server[3494]: 2017-04-23T22:53:14.241Z - info: Logging to file /var/log/realm-object-server.log at level 'info
Apr 23 16:53:14 link realm-object-server[3494]: Error: ENOENT: no such file or directory, open 'cloudkit_eckey.pem'
Apr 23 16:53:14 link realm-object-server[3494]:     at Error (native)
Apr 23 16:53:14 link realm-object-server[3494]:     at Object.fs.openSync (fs.js:641:18)
Apr 23 16:53:14 link realm-object-server[3494]:     at Object.fs.readFileSync (fs.js:509:33)
Apr 23 16:53:14 link realm-object-server[3494]:     at new CloudKitAuthProvider (/usr/lib/nodejs/realm-object-server/.build/src/node/services/au
Apr 23 16:53:14 link realm-object-server[3494]:     at Service.Object.keys.forEach.e (/usr/lib/nodejs/realm-object-server/.build/src/node/servic
Apr 23 16:53:14 link realm-object-server[3494]:     at Array.forEach (native)
Apr 23 16:53:14 link realm-object-server[3494]:     at new Service (/usr/lib/nodejs/realm-object-server/.build/src/node/services/auth/service.js
Apr 23 16:53:14 link realm-object-server[3494]:     at new Server (/usr/lib/nodejs/realm-object-server/.build/src/node/services/server.js:50:24)
Apr 23 16:53:14 link realm-object-server[3494]:     at ObjectServer.start (/usr/lib/nodejs/realm-object-server/.build/src/node/object-server.js:
Apr 23 16:53:14 link realm-object-server[3494]:     at Object.<anonymous> (/usr/lib/nodejs/realm-object-server/.build/src/node/bootstrap.js:33:1
Apr 23 16:53:14 link systemd[1]: realm-object-server.service: Main process exited, code=exited, status=99/n/a
Apr 23 16:53:14 link systemd[1]: realm-object-server.service: Unit entered failed state.
Apr 23 16:53:14 link systemd[1]: realm-object-server.service: Failed with result 'exit-code'.
Apr 23 16:53:15 link systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Apr 23 16:53:15 link systemd[1]: Stopped Realm Object Server.
Apr 23 16:53:15 link systemd[1]: Started Realm Object Server.
Apr 23 16:53:17 link realm-object-server[3820]: 2017-04-23T22:53:17.916Z - info: Logging to file /var/log/realm-object-server.log at level 'info
Apr 23 16:53:18 link realm-object-server[3820]: Error: ENOENT: no such file or directory, open 'cloudkit_eckey.pem'
Apr 23 16:53:18 link realm-object-server[3820]:     at Error (native)
Apr 23 16:53:18 link realm-object-server[3820]:     at Object.fs.openSync (fs.js:641:18)
Apr 23 16:53:18 link realm-object-server[3820]:     at Object.fs.readFileSync (fs.js:509:33)
Apr 23 16:53:18 link realm-object-server[3820]:     at new CloudKitAuthProvider (/usr/lib/nodejs/realm-object-server/.build/src/node/services/au
Apr 23 16:53:18 link realm-object-server[3820]:     at Service.Object.keys.forEach.e (/usr/lib/nodejs/realm-object-server/.build/src/node/servic
Apr 23 16:53:18 link realm-object-server[3820]:     at Array.forEach (native)
Apr 23 16:53:18 link realm-object-server[3820]:     at new Service (/usr/lib/nodejs/realm-object-server/.build/src/node/services/auth/service.js
Apr 23 16:53:18 link realm-object-server[3820]:     at new Server (/usr/lib/nodejs/realm-object-server/.build/src/node/services/server.js:50:24)
Apr 23 16:53:18 link realm-object-server[3820]:     at ObjectServer.start (/usr/lib/nodejs/realm-object-server/.build/src/node/object-server.js:
Apr 23 16:53:18 link realm-object-server[3820]:     at Object.<anonymous> (/usr/lib/nodejs/realm-object-server/.build/src/node/bootstrap.js:33:1
Apr 23 16:53:18 link systemd[1]: realm-object-server.service: Main process exited, code=exited, status=99/n/a
Apr 23 16:53:18 link systemd[1]: realm-object-server.service: Unit entered failed state.
Apr 23 16:53:18 link systemd[1]: realm-object-server.service: Failed with result 'exit-code'.
Apr 23 16:53:18 link systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Apr 23 16:53:18 link systemd[1]: Stopped Realm Object Server.
Apr 23 16:53:18 link systemd[1]: Started Realm Object Server.
Apr 23 16:53:21 link realm-object-server[3830]: 2017-04-23T22:53:21.339Z - info: Logging to file /var/log/realm-object-server.log at level 'info
Apr 23 16:53:21 link realm-object-server[3830]: Error: ENOENT: no such file or directory, open 'cloudkit_eckey.pem'
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
2017-04-23T23:39:25.885Z - info: sync-server: Connection[6]: Session[1]: Session terminated (session_ident=1).
2017-04-23T23:39:25.885Z - info: sync-server: Connection[6]: Connection closed by client: End of input
2017-04-24T00:52:10.611Z - info: Closing gracefully. Caught signal SIGTERM.
  </code>
</details>

**Comment by mrackwitz** [comment]
You're completely right with your expectations. What you describe is what is supposed to actually happen. I filed internal issues around improving the configuration validation for the authentication providers. We'll keep you up to date here. Thanks for bringing this up here!

**Comment by bigfish24** [comment]
Closing as this references ROS 1.x. Please reopen if a similar issues exists with ROS 2.0
