### ISSUE TITLE
Unable to locate package realm-object-server-developer

### ISSUE THREAD

**Issue by Nonnis-M** [realm/realm-object-server#177]
## Goals

Getting started with realm on a clean linux machine (where clean means "the provider just deliver it for me"

## Expected Results
To se a working realm object server

## Actual Results

I got this error "Unable to locate package realm-object-server-developer"

## Steps to Reproduce

I tried to setup realm on a linux machine just after the o.s. was installed. This is the server configuration:

Linux vmi111164 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
O.S: Linux Ubuntu 16.04 64bit

I've followed the setup instruction of the getting started realm section for Ubuntu 16.04:
curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | sudo bash
sudo apt-get update
sudo apt-get install realm-object-server-developer

at this point I get the error:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package realm-object-server-developer

That's all. Thanks in advance.

**Comment by istx25** [comment]
Hi @Nonnis-M. Thanks for reaching out about this. I wanted to apologize for the delay in getting back to you here. Somehow this issue fell through the cracks. Someone should follow-up with you soon here. Thanks for being patient! Cheers!

**Comment by exception** [comment]
I've just tried to d the same on a google cloud instance and it failed to locate the package.

**Comment by mokkun** [comment]
Having the same issue here on Ubuntu 17.04

**Comment by teotwaki** [comment]
@mokkun That is an unrelated issue. We only package for Ubuntu 16.04, so you not finding packages on Ubuntu 17.04 is expected.

**Comment by vahevia** [comment]
I'm having the same issue. I have ubuntu 16.04 64bit. I followed all the instructions and I keep getting the same message:  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
N: Ignoring file '50unattended-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
E: Unable to locate package realm-object-server-developer
If you could help me with this, I'll appreciate it a lot!

**Comment by vijaemanlapaz** [comment]
same here trying to install on raspberry pi 2

**Comment by nenadvulic** [comment]
same here Ubuntu/trusty

**Comment by nenadvulic** [comment]
@teotwaki do you have any workaround for < 16.04 ?

**Comment by alebsack** [comment]
I'm not sure what went wrong here, but here's what I've done on a fresh ubuntu 16.04 install:

```
$ curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | sudo bash
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/realm_realm.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
$ sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:5 https://packagecloud.io/realm/realm/ubuntu xenial InRelease
Reading package lists... Done
$ sudo apt-get install realm-object-server-developer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libyaml-cpp0.5v5
The following NEW packages will be installed:
  libyaml-cpp0.5v5 realm-object-server-developer
0 upgraded, 2 newly installed, 0 to remove and 150 not upgraded.
Need to get 63.9 MB of archives.
After this operation, 225 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libyaml-cpp0.5v5 amd64 0.5.2-3 [158 kB]
Get:2 https://packagecloud.io/realm/realm/ubuntu xenial/main amd64 realm-object-server-developer amd64 1.8.2-310 [63.7 MB]
Fetched 63.9 MB in 7s (8,765 kB/s)                                                                                                                             
Selecting previously unselected package libyaml-cpp0.5v5:amd64.
(Reading database ... 53810 files and directories currently installed.)
Preparing to unpack .../libyaml-cpp0.5v5_0.5.2-3_amd64.deb ...
Unpacking libyaml-cpp0.5v5:amd64 (0.5.2-3) ...
Selecting previously unselected package realm-object-server-developer.
Preparing to unpack .../realm-object-server-developer_1.8.2-310_amd64.deb ...
Generating RSA private key, 2048 bit long modulus
.........................................................+++
...................................................................................+++
e is 65537 (0x10001)
writing RSA key
Unpacking realm-object-server-developer (1.8.2-310) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Setting up libyaml-cpp0.5v5:amd64 (0.5.2-3) ...
Setting up realm-object-server-developer (1.8.2-310) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
```

What I can suggest is running `apt-get update` again and watching for any errors when pulling from packagecloud.io: `https://packagecloud.io/realm/realm/ubuntu xenial InRelease`.

**Comment by sytolk** [comment]
I have the same issue with Debian stretch. Install script run successful and create file:
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/realm/realm

deb https://packagecloud.io/realm/realm/debian/ stretch main
deb-src https://packagecloud.io/realm/realm/debian/ stretch main
```
but `aptitude update` failed:
```
Ign https://packagecloud.io/realm/realm/debian stretch InRelease
Err https://packagecloud.io/realm/realm/debian stretch Release
  404  Not Found
Ign http://dl.google.com/linux/chrome/deb stable InRelease
Ign http://dl.google.com/linux/earth/deb stable InRelease
Hit http://dl.google.com/linux/chrome/deb stable Release
Hit http://dl.google.com/linux/earth/deb stable Release
E: The repository 'https://packagecloud.io/realm/realm/debian stretch Release' does not have a Release file.
E: Failed to download some files
W: Failed to fetch https://packagecloud.io/realm/realm/debian/dists/stretch/Release: 404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by bigfish24** [comment]
Closing since this references ROS 1.x and the installation with 2.0 is now through NPM.

**Comment by revolter** [comment]
@bigfish24, But how do we remove the repository now? As it keeps throwing errors on every `apt-get update`.

**Comment by alebsack** [comment]
@revolter Check your `/etc/apt/sources.list.d` directory for any files with the name `packagecloud` in them, and remove them.  Then you can run `apt-get update`.
