### ISSUE TITLE
How do I test custom providers?

### ISSUE THREAD

**Issue by IsaiahJTurner** [realm/realm-object-server#195]
There seems to be no way to test it without building a full client. On top of that, how do I write log messages (either to the web UI log or elsewhere on the server)? I built a provider but get no output from it. The iOS app only says "Your request parameters did not validate."

**Comment by IsaiahJTurner** [comment]
Oh I see didn't realize I need to add "custom/" to the Provider in the iOS app. This leaves only one more question - are ids from `verifyIdentifier` unique to the provider or to the realm-object-server? Should I prefix them with the provider name if their could be collisions (same id + different provider = different people)?

**Comment by mrackwitz** [comment]
>How do I test custom providers? There seems to be no way to test it without building a full client.

That's unfortunately true so far. We're working on some refactorings to the built-in providers and might have something in the process of that which gives 3rd-party developers a better experience to test their own implementations.

>On top of that, how do I write log messages (either to the web UI log or elsewhere on the server)?

The custom provider API doesn't expose yet access to the central log which is also displayed in the web UI. For now you could use `console.log` and directly write to `stdout` or use a custom logging mechanism.

>are ids from `verifyIdentifier` unique to the provider or to the realm-object-server? Should I prefix them with the provider name if their could be collisions (same id + different provider = different people)?

IDs supplied by the `verifyIdentifier` implementation of an authentication provider are unique to the provider's namespace. You don't need to prefix them with the provider name.

**Comment by IsaiahJTurner** [comment]
@mrackwitz 

When you say they are unique to a namespace what do you mean by that?

For example, I have one provider JavaScript file and, copying from the docs, it returns name like this:
```js
static get name() {
    return 'custom/jwt';
}
```
But I use that provider twice in my `configuration.yml` such that:
```yml
custom/jwt:
  implementation: jwt.js
  server: 'https://myapp.com'
custom/jwt_development:
  implementation: jwt.js
  server: 'https://development.myapp.com'
```
And the IDs from `custom/jwt` and `custom/jwt_development` could overlap. Would this setup be properly namespaced?

**Comment by mrackwitz** [comment]
>And the IDs from `custom/jwt` and `custom/jwt_development` could overlap. Would this setup be properly namespaced?

Yes, this would be properly namespaced. This also means that you aren't able to interchange authorization acquired via one provider for the other provider.

**Comment by RiverbayChris** [comment]
It would be nice if there was a "Provider" column or property for each user in the Users section on the Dashboard, so we know where they come from.

**Comment by bigfish24** [comment]
@RiverbayChris this is awesome feedback, thanks!

**Comment by bigfish24** [comment]
this can now be done with the new custom auth in 2.0
