### ISSUE TITLE
After update , cannot run server

### ISSUE THREAD

**Issue by saturngod** [realm/realm-object-server#196]
After doing , 

    apt-get upgrade

I cannot open the realm object server. So, I did

    apt-get remove realm-object-server

and install again.

After installing, I enable the server and I got following error.

```
sudo systemctl enable realm-object-server
Synchronizing state of realm-object-server.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable realm-object-server
update-rc.d: error: initscript does not exist: /etc/init.d/realm-object-server
```

**Comment by kvap** [comment]
@saturngod can you tell us the name and version of the server OS that you use here? And also the  version of `realm-object-server` package before and after the upgrade.

**Comment by saturngod** [comment]
I am running on Ubuntu 16.04. Before update, I am not sure about bersion. It may be version 1 or 0.9 beta. Now all the data gone :( . I need to remove and clean all the realm server data to run realm object server. Try to replace old realm file and it's showing time out.

**Comment by kspangsege** [comment]
Probably related to https://github.com/realm/realm-sync/issues/1341.

**Comment by kspangsege** [comment]
@alebsack I'm reassigning to you as representing the ROS team, as this looks like an issue with the cration of the Debian package for ROS.

**Comment by kspangsege** [comment]
Oh, you are already assigned :-)

**Comment by bmunkholm** [comment]
Related to 1.x.
