### ISSUE TITLE
Fine-grained (object-level) permissions

### ISSUE THREAD

**Issue by dsjstc** [realm/realm-object-server#22]
Creating this issue because it's a dealbreaker for my client-server POS app:  I see no way to establish user-level or group-level control over object modification.

EG: In a point-of-sale system, all users need to be able to _view_ product descriptions and prices.  But only a manager should be able to _modify_ the products.  When money is on the line, I cannot rely on all clients being trustworthy.

**Comment by teotwaki** [comment]
Hi @dsjstc,

I'm sure you've already thought of this, but currently, I would recommend that you create separate Realm databases. One containing the inventory of items, and another one containing orders, or whatever your POS does.

The typical implementation for this kind of feature, using the Enterprise Edition, is to have clients create a PurchaseRequest object (or something along those lines), which then gets approved by the server-side event handler. This guarantees that when the client gets its updated object back, with the "approved" or "order finalised" status, you know your backend is up to date.

I'll rename this issue to track the request for fine-grained permissions, in the mean time.

**Comment by dsjstc** [comment]
Makes sense.  I still see a problem with a malicious POS directly modifying things it should only be able to read, but perhaps the Enterprise server has a way to block those changes.

I didn't find a detailed explanation of the Enterprise features beyond the one-word descriptions on the pricing page -- some more detail might be a useful thing to publish to the world.

**Comment by teotwaki** [comment]
Hi dsjstc,

Indeed, the Enterprise version does allow to closely monitor what goes on, and intervene on changes as they occur. We're currently working on making the Enterprise (and Pro) versions more visible.

Thanks,

**Comment by DiogoAndre** [comment]
> We're currently working on making the Enterprise (and Pro) versions more visible.

Looking forward to see some more details on the Pro version! 😄

**Comment by ianbradbury-bizzibody** [comment]
@teotwaki - Please can I check.  The conversation thread gives me a hint that object permissions might only be available to Enterprise customers.  Am I over reacting?  I need to know as I will need to find an alternative technology - quickly - if true.

**Comment by teotwaki** [comment]
@ianbradbury-bizzibody That's not what I said. I said that at the moment we don't support object-level permissions, however that it was possible to emulate using the Enterprise Edition features. Object-level permissions are on our roadmap.

**Comment by ianbradbury-bizzibody** [comment]
@teotwaki - Thank you for clearing that up.

**Comment by dsjstc** [comment]
The most basic level of my functionality requirement is now addressed by [PermissionChange](https://realm.io/news/realtime-collaboration-now-for-every-mobile-developer/).  Still leaving the issue open because it's still not object-level control.

**Comment by mort3m** [comment]
@dsjstc - Could you elaborate if "object-level permissions" is something we will see soon or is it rather far away? I need to select a technology for my project and this is something I absolutely need in the future. 

I appreciate all your hard development work and your open conversation with the community. Keep things up!

**Comment by bigfish24** [comment]
"Object-level permissions" are not on the immediate roadmap. We are currently laying the groundwork, but it will take some time. What I would love to know from the community is how you would like this to be implemented. When we discuss internally, we call this "partial synchronization" since today, permissions and sync are all based on the Realm level. This is still very flexible, because you can split your data up into many Realms, either user-specific or shared and then sync only the Realms needed (at a given time), to "partially sync" the larger data set managed by the server.

However, we realize that there are situations where it would be beneficial to have a single large dataset in 1 Realm, with mobile clients only syncing a subset of this large Realm.

How do you imagine this working in your perfect scenario? For example, this could be query-based where you could request a query in a Realm that is synced with the larger Realm, such that only those objects that match the query will be synced.

One thing to keep in mind, is that this will have implications on the client SDK API. Today, because sync works on the Realm level, if you open a synchronized Realm, you are guaranteed that you can traverse links between objects. Once you add partial sync, this breaks and there needs to be a way to handle links to an object that may not have been synced locally. Furthermore, in my example above with a query-based approach, how do you handle object graphs? Cyclic graphs would mean that a query would end up syncing all children, which might potentially be the entire data set. One way to handle this would be to define "weak" relationships in the schema to inform such system where to break the graph when syncing.

Additional feedback from the community would be very beneficial in guiding which path we take. Right now there is still time because we are first working on the basic primitives server-side that would support partial sync.

**Comment by dsjstc** [comment]
My use-case (disconnected point-of-sale) would work best with 
server-side restriction of CRUD to specified clients.  So partial sync 
isn't a full solution for me.

Specific use cases:

- view-only client that has full read-only access to the entire contents 
of a table.
- restricted sales client that can create, read and update its own 
objects, but nobody else's.
- sales manager that can do full CRUD on items created by specific sales 
clients.

Implementation:

class RealmRestrictedObject extends RealmObject.  The class has five 
permissions-lists, each consisting of a list of client-identifiers.   
one for each of Create, Read, Update, Delete, and Permissions. Only 
clients on the Permissions list are allowed to modify the permissions-lists.

Any request at the MOS involving a RealmRestrictedObject is first 
checked that it's coming from a client with the appropriate permission.

I haven't thought much about user<-->client mapping.  At present MOS 
doesn't prevent one user from being logged in on multiple clients, so 
it's probably best to keep them distinct.  I'm actually not sure whether 
permissions need to be client-based or user-based.

**Comment by bigfish24** [comment]
@dsjstc first, this is incredibly helpful. I will definitely make sure it is shared internally. Secondly, could you describe your data model? Part of me looks at this and says there could be a way to do it today with the Realm access control capabilities.

**Comment by bigfish24** [comment]
Another thing to keep in mind, is that currently there is a limitation on the client SDK that prevents read-only synchronized Realms (even though you can set a Realm to be read-only in our permission system). We will be resolving this in the coming weeks, so this could open up a way to do it on the Realm level vs object.

**Comment by dsjstc** [comment]
Thanks Adam.  I haven't fully developed my data model because I was trying to make it go as far as I could without those capabilities.  The key elements are:

```
class Product
  String description
  Double price

class SoldItem
  Product type
  Long uniqueSerial

class Sale
  List<Product> soldItems
  ClientID seller;
```

In my case, an individual seller should be able to add new sales.  It is critical that they be prevented from modifying sales after the fact.  Only managers can do that.

I also need an untrusted View client that can get a sum total of the price of all SoldItems in all Sales, but cannot modify anything, ever.

**Comment by ianbradbury-bizzibody** [comment]
@bigfish24 - Firstly.  Thank you for the opportunity to give my thoughts/needs.

**Scenario 1**

3 types of user.  [Admin], [Non-Subscriber] and [Subscriber].
2 types of data.  [General Information] and [User Feedback].

[Admin]’s have full CRUD across all objects and all records.

[Non Subscriber]'s can only READ [General Information] objects - they can read all the [General Information].

[Subscriber]'s can READ the [General Information] objects, and, they can CREATE and READ [User Feedback] objects - they can READ ALL the [General Information] and READ ALL the [User Feedback] objects.


**Scenario 2**

This scenario is very complex - so if I don’t describe it clear enough please let me know and I can attempt to be clearer.

I am describing the scenario in the abstract as I can't describe in detail.

There are 4 types of user.  [Admin], [Owner], [Editor] and [Reader]

Envisage a [Magazine].  The [Magazine] has an [Owner].  The [Owner] has full CRUD access to all Realm objects that relate to "their" [Magazine].  There will be multiple [Magazine] objects in the Realm.

The [Magazine] is divided into [Section]'s.  Access to [Section]'s is secured.  [Editors] and [Readers] are given access to a subset of [Section]'s.

[Section]'s are made up of [Article]'s.  [Editors] have CRUD access to all the [Article]'s in the [Section]'s where they are [Editors].  [Readers] have access to a subset of [Article]'s - they do not necessarily have access to all [Article]'s in a [Section]'s where they have access to.

**Comment by ianbradbury-bizzibody** [comment]
@bigfish24  -  Picking up on something you mentioned.

Security via a query.  

I'm not sure about security via a query.  That strikes me as potentially dangerous.

But I am interested in the idea of selective sync via a query.  In cases where security is not an issue - being able to select which objects are synced based on a query would be bloody brilliant.  (But that's another ticket)

**Comment by neokree** [comment]
There was any update on this feature? 
With object-model permission it will be possible to use Realm Mobile Platform instead of relational database + RESTful webservice, which would be awesome for building faster and better web applications.

**Comment by bmunkholm** [comment]
Object level permissions has now been implemented.
