### ISSUE TITLE
HTTP: Failed to switch protocols (response status = 502)

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-object-server#221]
From:  https://github.com/realm/realm-mobile-platform/issues/187#issuecomment-305346254

>I am also seeing this (potentially related) error fairly frequently.

```
2017-05-31 16:19:28.703 Memlogos[5159:195965] Sync: Connection[2]: Reading failed: End of input
2017-05-31 16:19:28.703 Memlogos[5159:195965] Sync: Connection[2]: Connection closed due to error
2017-05-31 16:19:28.704 Memlogos[5159:195965] Sync: Connection[2]: Resolving 'realm.mydomain.com:80'
2017-05-31 16:19:28.705 Memlogos[5159:195965] Sync: Connection[2]: Connecting to endpoint '192.241.205.154:80' (1/1)
2017-05-31 16:19:28.731 Memlogos[5159:195965] Sync: Connection[2]: Connected to endpoint '192.241.205.154:80' (from '172.19.248.230:55220')
2017-05-31 16:19:29.922 Memlogos[5159:195965] Sync: Connection[2]: HTTP: Failed to switch protocols (response status = 502)
2017-05-31 16:19:29.922 Memlogos[5159:195965] Sync: Connection[2]: Connection closed due to error
```

I have about 40K objects in my Realm. I also seem to stop getting notifications on changes to the collection but I'm still investigating that.

**Comment by kspangsege** [comment]
@bigfish24 Have a look at the resolution suggested in this issue: https://github.com/realm/realm-mobile-platform/issues/193#issuecomment-303441769.

**Comment by bigfish24** [comment]
So the answer is in Nginx:
>change this line
>`proxy_set_header Connection "upgrade";`
>to
>`proxy_set_header Connection "Upgrade";`

**Comment by bigfish24** [comment]
If so can we close this?

**Comment by kspangsege** [comment]
I don't know if it is exactly the same issue, but it looks like it is. Would be good if he can confirm that it solves the problem.

cc @morten-krogh

**Comment by mrackwitz** [comment]
It doesn't seem as this would be the same problem as in #193, if you look into the further conversation of the referred issue, you'll see that this user was previously affected by this problem and could resolve this issue with the solution proposed by Morten.

**Comment by kspangsege** [comment]
@mrackwitz Ok, I see your point. @morten-krogh Can you take it from here? I suppose your new log messages could help in diagnosing this.

**Comment by morten-krogh** [comment]
I can take it from here. Is it issue #187?

**Comment by kspangsege** [comment]
@morten-krogh https://github.com/realm/realm-mobile-platform/issues/187 is mostly on a different subject, but this issue was mentioned in a comment (https://github.com/realm/realm-mobile-platform/issues/187#issuecomment-305346254), so I guess @bigfish24 decided to elevate that comment to a new separate issue (this one).

**Comment by morten-krogh** [comment]
Sorry for my lack of understanding of the context here. 

What is the issue I am supposed to look into? Is there a user I can communicate with?
The snippet above is not enough. We can release a new version of Sync with the changes I made today, and have them use that. Then we can look at the log file.

But in what issue do I talk directly to the user?

**Comment by kspangsege** [comment]
@morten-krogh This issue was an offspawn from https://github.com/realm/realm-mobile-platform/issues/187, so it is the same user, namely @FreudGit .
