### ISSUE TITLE
 start-object-server.command on macOS gets 404 page in browser - need a slight startup delay

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-object-server#230]
## Goals

Trying to start ROS/PE from the `start-object-server.command` under macOS

## Expected Results

`start-object-server.command` should run and I get redirected to the signup or login page in the ROS dashboard.

## Actual Results

Got a 404 page from the browser

## Steps to Reproduce
start ROS from the `start-object-server.command ` 

Basically the command is launching the browser before the server has a chance to finish its startup sequence...hitting reload after a few seconds shows the server is in fact running... it just wasn't ready at the moment the command ran.

Adding a 3-5 second delay should fix the issue.

## Code Sample

N/A
## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ x] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6) 1.81
- Client SDK Version: ? N/A
- Client OS & Version: ? macOS 10.12.5

## Logs

N/A
<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by bmunkholm** [comment]
Not a problem in ROS 2.0
