### ISSUE TITLE
Stability Issues on Realm Object Server

### ISSUE THREAD

**Issue by 3hugg3r** [realm/realm-object-server#236]
Ubuntu 16.04 LTS on Linode,

I am having a stability issue with the server.
With only 8 open connections it takes 80% of the CPU. It also seems that it uses only one core.

I was hoping for couple hundred connections but it the server runs on 100% with 8 I am expecting a lot of issues with a couple more.

Server jumps to 100% often after reconnect - especially if we restart the app on our phones at the same time.

Any Ideas?
Thank you,
Andre

https://www.dropbox.com/s/s7k34hlpknua5mt/Screenshot%202017-07-09%2008.51.53.png?dl=0
https://www.dropbox.com/s/qp36j9d3vhoh2pi/Screenshot%202017-07-09%2008.52.43.png?dl=0
https://www.dropbox.com/s/63ht887c8vcnl60/Screenshot%202017-07-09%2009.10.51.png?dl=0

Some of the server logs:
https://pastebin.com/PeYFMsXz

Our app code:
package com.XXXXXXXX.gateway.Model.Realm;
import android.provider.Settings;
import android.util.Log;
import com.hyperlocal.gateway.Model.BootCompletedReceiver;
import com.hyperlocal.gateway.Model.MyApplication;
import io.realm.ObjectServerError;
import io.realm.Realm;
import io.realm.SyncConfiguration;
import io.realm.SyncCredentials;
import io.realm.SyncUser;
public class RealmSyncer implements SyncUser.Callback {

    private static final String email = "someuser";
    private static final String password = "somepassword";
    private static final String LOG_TAG = "RealmSyncer";
    private static Boolean isLogin = false;
    public RealmSyncerDelegate delegate;
    public RealmSyncer(RealmSyncerDelegate delegate) {
        this.delegate = delegate;
    }
    public void login() {
        if (!isLogin) {
            SyncUser.loginAsync(SyncCredentials.usernamePassword(email, password, false), MyApplication.AUTH_URL, this);
        }
    }
    public String getRealmURL() {
        return MyApplication.REALM_URL();
    }
    private void setActiveUser(SyncUser user) {
        SyncConfiguration defaultConfig = new SyncConfiguration.Builder(user, getRealmURL()).build();
        if (this.delegate != null) {
            delegate.realmSyncerSuccessfullySynced(defaultConfig, true);
        }
    }
    @Override
    public void onSuccess(SyncUser user) {
        Log.d(LOG_TAG, "SUCCESS LOGINNING");
        isLogin = true;
        setActiveUser(user);
    }
    @Override
    public void onError(ObjectServerError error) {
        Log.d(LOG_TAG, "Error LOGINNING");
        String errorMsg;
        switch (error.getErrorCode()) {
            case UNKNOWN_ACCOUNT:
                errorMsg = "Account does not exists.";
                break;
            case INVALID_CREDENTIALS:
                errorMsg = "The provided credentials are invalid!"; // This message covers also expired account token
                break;
            default:
                errorMsg = error.toString();
        }
        Log.d(LOG_TAG, errorMsg);
        if (this.delegate != null) {
            delegate.errorSynced(error);
        }
    }
}

**Comment by bmunkholm** [comment]
We are investigating a similar issue (#228) for another user. This may be related.

**Comment by Zhuinden** [comment]
I'm guessing this should be solved with the release of RMP 2.0

**Comment by bigfish24** [comment]
This issue should be resolved with ROS 2.0
