### ISSUE TITLE
Tool for creating schemas across bindings

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-server#24]
Working with Sync has made it abundantly clear that creating schemas across languages is a pretty hard problem, and we also mess it up frequently internally. 

The following things will make this easier:

1)  Agree on a format for a cross platform language for specifying schemas either as a new "language" or perhaps just use the JSON format that JS already uses?

2) Online tool for doing it on the fly. Will make one-off conversions really easy. It would also be cool if such a tool could validate the schema given a specification.

3) A command line tool for generating language specific classes. Useful for continuous development by multiple teams. Needs to be written in a cross-platform language, perhaps Java or Ruby? Could also be used as the backing code for 2).

**Comment by alazier** [comment]
I think standardizing on a JSON schema would take us a long way towards achieving all of these things. We already specify the schema as JSON in the JS binding. I would be happy to refactor this code to use `json.hpp` so that the other bindings can easily import schema of the same format.

**Comment by AndyDentFree** [comment]
I support an actual code generator as well as a JSON binding.

Implementing the code generator in JS means it can be hosted online as well as inside utility apps on all platforms.

For one thing, there is a **huge** difference in dotnet between having class declarations and using a dynamic interface. We weave our code at compile time and this is far more optimal than dynamic access.

Note also As of 2 Jan 2017, dynamic access in dotnet is [still pending](https://github.com/realm/realm-dotnet/issues/778)!

**Comment by gpulido** [comment]
I see this problem very similar to the protobuff generators:
A schema definition language, and a generator that would create the schema.
I have some concerns regarding versioning the schema, and the "not generated" code that should have to be moved out of the main model classes (not empty constructors, business logic). But that could be managed without problems by the developers using helper classes for example.
My use case is to be able to use a model with more than 40 type objects in Java and in a Node.js server using sync to synchronize both, and without having to create again the entire model in Node, and avoiding modification issues.

**Comment by bmunkholm** [comment]
Studio can now export schemas in various languages
