### ISSUE TITLE
Object Server Search

### ISSUE THREAD

**Issue by misterlib** [realm/realm-object-server#266]
Using the search bar on v.1.8.3 seems incapable of returning a result

## Goals

Search for the Owner name in the search field rather than clicking through the pagination and manually trying to spot the owner.

## Expected Results

Type the Owner name into the search field and have that row be returned for access.

## Actual Results

Type the Owner name into the search field, and 0 results are returned, no matter if the Owner is on page 50 or page 1.  It just doesn't ever return a result.

## Steps to Reproduce

Type in the search field, any letter, and all rows instantly disappear.

## Version of Realm and Tooling

- Realm Object Server Version: 1.8.3
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: CentOS 7

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by morten-krogh** [comment]
Thanks for reporting this bug.
Did you use the id of the owner?

Anyway,  we will soon release a new UI for ROS where it is possible to find all Realms for a user.

**Comment by misterlib** [comment]
I'm not sure if it is what you call the ID (because it doesn't say ID anywhere in the UI), but I use the name that is shown in the Owner column.  I see that searching for the random string of characters in the Path column works, but not the human readable name from the Owner column.  Which, there's no reason that I would know the path from a customer service standpoint of needing to find a user's realm, so searching by the path is useless.

BTW, I don't consider this closed since it is clearly not working still.

**Comment by morten-krogh** [comment]
I agree that the search should work on the name not just the id.

The reason I closed it is that we will release a new UI that solves this.
We will not be doing any work on fixing the current version.

I have reopened it. We can keep the issue open.

**Comment by misterlib** [comment]
Any timeline for the new release?

Every day I click through my entire list of hundreds of realms, manually looking for the right names in order to support customers.  Losing so many hours because search is manual.

**Comment by bigfish24** [comment]
@misterlib you can check out the beta here: https://realm.gitbooks.io/realm-object-server/

**Comment by bigfish24** [comment]
With ROS 2.0 the Realm search lives in Realm Studio vs. a server dashboard so going to close this
