### ISSUE TITLE
Can not uninstall

### ISSUE THREAD

**Issue by Dumanix** [realm/realm-object-server#272]
I have installed and couldn't use it. I used npm uninstall realm but it is still there. I can only run my app on a simulator. When i try to run in my phone using xcode, i am getting error "ld: library not found for -lRealmReact"

Can someone help how to completely remove realm?

**Comment by bmunkholm** [comment]
@Dumanix Could you please describe in details (with exact commands) how you have installed Realm and how you are trying to uninstall it?
Also how are you referring to Realm since you are still getting references to it?

**Comment by bmunkholm** [comment]
Closing due to no response
