### ISSUE TITLE
Taking Too much storage

### ISSUE THREAD

**Issue by saturngod** [realm/realm-object-server#274]
I am using realm mobile platform in Ubuntu 17.04 with 30 GB external HD. After over 1000 records , the disk is full. I already disable the backup. Is there any missing in my config ? It take more disk storage than other database for the records.

**Comment by bmunkholm** [comment]
@saturngod Please keep the issue template that's provided and fill out the details, so we can better help you.
E.g. which version are you using? Can you share more details? Can you let us know how often these records are being updated?

**Comment by bmunkholm** [comment]
Closing due to no response.
