### ISSUE TITLE
realm-object-server-developer fails during install onto Ubuntu at Digital Ocean

### ISSUE THREAD

**Issue by larryseyer** [realm/realm-object-server#278]
I believe I have found a bug in the installation of a new Realm Mobile server using Ubuntu on Digital Ocean  ... (using sudo apt-get install realm-object-server-developer)

I followed the installation instructions found at realm.io and I consistently get an error when trying to install the server.   

Having Destroyed and rebuilt a server several times now each time I get the same results.

After installing, the system tells me the realm-object-server.service is running via the status command line:

● realm-object-server.service - Realm Object Server
   Loaded: loaded (/etc/systemd/system/realm-object-server.service; enabled; ven
   Active: active (running) since Sun 2017-10-22 01:15:46 UTC; 2min 4s ago
 Main PID: 2777 (realm-object-se)
    Tasks: 22
   Memory: 56.9M
      CPU: 2.883s
   CGroup: /system.slice/realm-object-server.service
           ├─2777 /usr/lib/realm-object-server-developer/node/bin/node /usr/bin/
           └─2794 /usr/lib/realm-object-server-developer/node/bin/node /usr/lib/

I can login to the realm server using a web browser pointing to http://x.x.x.x:9080/ with no problems.

However, when trying to connect to the realm server using either the _Realm Browser_ or the _Realm Console_, I get the spinning wheel of death...  It never connects.

It seems to always fail here:

sudo apt-get install realm-object-server-developer

Here is what is failing:

Failed at the lzma-native@3.0.1 install script 'node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lzma-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

Is this a bug in 2.0?

**Comment by larryseyer** [comment]
I have more information after trying it another droplet...

Failed at the lzma-native@3.0.1 install script 'node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lzma-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

**Comment by nirinchev** [comment]
The installation procedure for 2.0 is different from the one for 1.x and it seems like you are following the instructions for 1.x - 2.0 is installed via npm, not apt. Can you verify you're following the [correct getting started guide](https://realm.io/docs/get-started/installation/developer-edition/#installing-realm-object-server)?

**Comment by larryseyer** [comment]
Yes, I'm sure.

Watch this:

https://www.youtube.com/watch?v=qxx837kVceA

**Comment by nirinchev** [comment]
I think you missed a step:
```
npm install -g node-gyp
```

After running `node -v`. Additionally, when installing ROS from npm, because you're doing it as root, you need to add `--unsafe-perm`:

```
npm install -g --unsafe-perm realm-object-server
```

We have it as a comment in the snippet, but I guess it's not obvious enough, I'll bring it up with the docs team to figure out how to make it clearer.

**Comment by larryseyer** [comment]
Thank you.  

I was able to get the Realm server running as long as the terminal window is open... but the moment I close my terminal window, it no longer works.

Also, going to http://x.x.x.x:9080 displays only the following:

Cannot GET /

Realm Console seems to work, however.

L

**Comment by bmunkholm** [comment]
@larryseyer That's a great bug report! Thanks! What tricks us up in the first description is the "sudo apt-get install realm-object-server-developer", which is not part of the new install instructions.

I tried to replicate the error, but starting a completely new droplet (1 GB) worked flawlessly. BUT if I make an error like forgetting the --unsafe_perm, then it's very hard to get into a working state again.

So could it be that you have made some error before, i.e. forgetting to pass on --unsafe-perm?

Have you tried to install with a completely new droplet? That works for me.

**Comment by bmunkholm** [comment]
If you close the terminal window, the process ROS is running in is also stopped. Consider leaving the terminal open if you are only testing, or use pm2 (https://realm.io/docs/realm-object-server/latest/#going-into-production).
We have removed the web dashboard and replaced it with Realm Studio.

**Comment by larryseyer** [comment]
The documentation on the website is somewhat confusing to me.  In some places it says one thing and in others it says something else.  

I apologize if I am missing something here.   

Also, the videos have a step-by-step explanation that I followed originally and they differ from the current website text... so I guess you guys are in transition from 1.0 behavior to 2.0 behavior?   

In the meantime, those of us who are just getting starting with Realm are a little confused as to what to do.

I will try what you suggested with the pm2 and see if I can test my builds using the server in that configuration.

The goal is to have a running Realm server in developer mode (running on it's own without a terminal open on my local machine) so that I can do the tests I need to do locally while developing my app.

Thanks for your help.

L

**Comment by bigfish24** [comment]
@larryseyer apologies for the confusing docs, I have created issues to improve them based on your feedback. Let us know if you can get it working with PM2 and `ros init` which is the recommended way to setup for production use.

**Comment by larryseyer** [comment]
Thank you.  

I installed PM2 and gave it a whirl...   It seemed to install just fine.  I need to read up more about how to use it. 

For now, I think I will destroy the current server and wait until you guys have better documentation.

During the programming part of this project I need to know that any bugs I find are actually MY bugs and not something that's not right with the server.

I can always add the Realm server part of the process later.  In the mean time, I will get back to programming using the Realm database.

Thank you for your help with this.   

I'll check back in a few days and try it again.

All the best to you!

L

**Comment by ianbradbury-bizzibody** [comment]
@bigfish24 - Hey Adam.  Please please please can you beef up the documentation regarding configuring ROS (v2)?

The documentation that exists is super light - such that I've been unable to figure how to configure ROS to use HTTPS!  

I can get it to run HTTPS using the command line switches - but no idea how to configure using a script for development/production.  Improved documentation in this area would be great.

**Comment by leonardarnold** [comment]
Hey guys. I do not want to create a new issue because mine is the same as the headline says. Ubuntu + DigitalOcean the install does not work for me. 
Instead of `nvm install --lts` i used `nvm install 6.11.4` to have the exact version (--lts is on 6.11.5 now).
To install realm i used: `root@realm:~# npm install -verbose -g --unsafe-perm realm-object-server`

Here is the complete commandline output from the fresh Ubuntu 16.04.3 LTS vm from Digital Ocean:
[digitalocean_ubuntu_ros.log](https://github.com/realm/realm-object-server/files/1425331/digitalocean_ubuntu_ros.log)

I also tried CentOS once but i had the same issue. Am I missing something or is it a bug?
Thank you

**Comment by bmunkholm** [comment]
@leonardarnold Is it a 1GB instance? We have seen some problems with Digital Ocean 512M, nut usually sooner in the Node install process.

**Comment by leonardarnold** [comment]
@bmunkholm no. It is a 512MB Memory and 20GB Disk instance.

**Comment by nirinchev** [comment]
Can you try upgrading the instance memory? We're working on a fix to reduce the memory requirements when installing but until that's ready, increasing the VM memory is a quick workaround. After the installation, you can reduce it to the original value.

**Comment by Damnum** [comment]
Downgrading from node v8.9.0 (installed via `nvm install --lts`) to v6.11.4 as @leonardarnold suggested, fixed the issue for me. In addition, 512MB memory did not work. 1 GB works.

**Comment by bmunkholm** [comment]
@leonardarnold Did you get this resolved going to 1GB?

**Comment by leonardarnold** [comment]
@bmunkholm sorry, somehow i missed that here. No I didn't try it. It was for a personal project and I had no time to try out. I used AWS and now it works

**Comment by bmunkholm** [comment]
Good to hear. I'll close this then.

**Comment by codegrue** [comment]
Following the install instructions, both "automated" and "manual", I consistently get this error at "npm start":

npm ERR! my-ros-app@1.0.0 build: `rm -rf dist; ./node_modules/.bin/tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the my-ros-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by codegrue** [comment]
Also, the docs show both "npm start" and "ros start". I assume "ros start" is deprecated so i think this should be mentioned or remove it from the CLI completely.

**Comment by hatunike** [comment]
I get the same thing as @codegrue , on fresh install following the instructions exactly I get that error every time.

For me, `ros start` works to start the server. `npm start` does not work.

I haven't used realm object server since 1.0, but now with 2.0 I can't get a fresh install up and running, that stays running.

I've upgraded my digital ocean to 1gb ram. Still no luck.

I'm fine using `ros start` for now because it works. But doesn't persist running on the server as soon as I close my ssh session. (I haven't tried going through the deployment guide yet - if that has any further info). Mostly I'm just concerned that I can't follow any of the documentation about using `npm` commands because everyone of them fail. From what I can tell `./node_modules/.bin/tsc` just doesn't exist.
