### ISSUE TITLE
Check if a certain permission has been applied to a realm (sync)

### ISSUE THREAD

**Issue by jaisontj** [realm/realm-object-server#281]
## Goals
I have a few realms which I want to share between different users. I have an admin app which creates these tables of type T1 at realm paths of /tableName and then applies a user wide read permission on these (UserCondition.noExistingPermissions()). Similarly, I have tables of type T2 at paths /tableName which require a user wise Write permission. Currently, each time the app starts, I apply these permissions to each of these tables individually.

My question is to know if there is a better way to do this ?

**Comment by morten-krogh** [comment]
Are the tables in the same Realm. You cannot have tables with different permissions in the 
same Realm. 

But you should not have to set permissions every time you start the app. The permissions remain.

**Comment by jaisontj** [comment]
I am using the realm object server, my understanding is that each table is a different realm when using ros. Hence setting different permissions for each realm works. (Is this correct?)

How do I check whether a certain table(realm) already has the required permissions I want ?

**Comment by morten-krogh** [comment]
Each Realm has its own permissions.
If you put one table in each Realm, each table will have its own permissions.
Remark that it is very common to have multiple tables in one Realm. In that case, all the tables 
share permissions.

You can check permissions as an administrator using Realm studio.
If you want to check it from the app, you can use the API described here

https://realm.io/docs/javascript/latest/#retrieving-permissions

**Comment by jaisontj** [comment]
Apologies for the late reply. Thank you for your response.
