### ISSUE TITLE
ROS 2.0 and CloudkitAuthProvider

### ISSUE THREAD

**Issue by molind** [realm/realm-object-server#282]
## Goals

Authenticate user using CloudkitAuthProvider

## Expected Results

User is authenticated or meaningful error is returned

## Actual Results

Internal server error happened. There is no check on userInfo inside error, but it tries to read reason from it. As result an exception inside catch block.
```
realm_1  | error: Internal server error: TypeError: Cannot read property 'reason' of undefined
realm_1  |     at CloudkitAuthProvider.<anonymous> (/realm/server/node_modules/realm-object-server/dist/auth/cloudkit/CloudkitAuthProvider.js:48:33)
realm_1  |     at throw (native)
realm_1  |     at rejected (/realm/server/node_modules/realm-object-server/dist/auth/cloudkit/CloudkitAuthProvider.js:5:65)
realm_1  |     at process._tickCallback (internal/process/next_tick.js:109:7)
```

## Steps to Reproduce

Setup CloudKit authentication. Try to authenticate.

## Code Sample

```
import { BasicServer } from 'realm-object-server'
import { CloudkitAuthProvider } from "../node_modules/realm-object-server/dist/auth/cloudkit/CloudkitAuthProvider"
import { FacebookAuthProvider } from "../node_modules/realm-object-server/dist/auth/facebook/FacebookAuthProvider"
import { GoogleAuthProvider } from "../node_modules/realm-object-server/dist/auth/google/GoogleAuthProvider"
import { PasswordAuthProvider } from "../node_modules/realm-object-server/dist/auth/password/PasswordAuthProvider"

import * as path from 'path'

const server = new BasicServer()

// Add the Key ID, private key path, container ID and environment information
let cloudKitProvider = new CloudkitAuthProvider(
  {
    container: 'iCloud.com.bodunov.galileo',
    // For production deployment on the App Store, you must specify 'production'
    environment: 'production',
    keyId: 'removed',
    privateKeyPath:  '/etc/realm/cloudkit_eckey.pem'
  }
)

let facebookProvider = new FacebookAuthProvider()

let googleProvider = new GoogleAuthProvider(
  {
    clientId: 'removed'
  }
)

let passwordProvider = new PasswordAuthProvider(
  {
    autoCreateAdminUser: false,
    saltLength: 32,
    iterations: 10000,
    keyLength: 512,
    digest: "sha512"
  }
)

server.start(
  {
    dataPath: '/data/realm',
    authProviders: [ passwordProvider, facebookProvider, googleProvider, cloudKitProvider ]
  }
).then(
  () => {
    console.log(`Your server is started `, server.address)
  }
).catch(
  err => {
    console.error(`There was an error starting your file:`, err)
  }
)
```

## Version of Realm and Tooling

- Realm Object Server Version: 2.0.4
- Flavor:
  - [X] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: Ubuntu 16.04 inside docker container
- Client SDK Version: 3.0.0
- Client OS & Version: iOS 11.0.0

## Logs

<details>
  <summary>log</summary>
  <code>
evgen@vmap1:~/docker/realm-dev2$ docker-compose up
Recreating realmdev2_realm_1
Attaching to realmdev2_realm_1
realm_1  | 
realm_1  | > my-ros-app@1.0.0 start /realm/server
realm_1  | > npm run build && node dist/index.js
realm_1  | 
realm_1  | 
realm_1  | > my-ros-app@1.0.0 build /realm/server
realm_1  | > rm -rf dist; ./node_modules/.bin/tsc
realm_1  | 
realm_1  | info: Realm Object Server version 2.0.4 is starting
realm_1  | info: Realm sync server started ([realm-core-4.0.2], [realm-sync-2.0.2]) service=sync
realm_1  | info: Directory holding persistent state: /data/realm/sync/user_data service=sync
realm_1  | info: Operating mode: master_with_no_slave service=sync
realm_1  | info: Listening on 127.0.0.1:43921 (sync protocol version 22) service=sync
realm_1  | info: sync-client: Connection[1]: Connected to endpoint '127.0.0.1:43921' (from '127.0.0.1:58996')
realm_1  | info: sync-client: Connection[2]: Connected to endpoint '127.0.0.1:43921' (from '127.0.0.1:58998')
realm_1  | info: sync-client: Connection[3]: Connected to endpoint '127.0.0.1:43921' (from '127.0.0.1:59000')
realm_1  | info: Starting auth provider 'password'
realm_1  | info: sync-client: Connection[4]: Connected to endpoint '127.0.0.1:43921' (from '127.0.0.1:59002')
realm_1  | info: Starting auth provider 'facebook'
realm_1  | info: Starting auth provider 'google'
realm_1  | info: Starting auth provider 'cloudkit'
realm_1  | info: 127.0.0.1 - GET /realms/files/%2F__admin HTTP/1.1 200 41 - 4.653 ms
realm_1  | info: 127.0.0.1 - GET /realms/files/%2F__revocation HTTP/1.1 200 46 - 0.948 ms
realm_1  | info: 127.0.0.1 - GET /realms/files/%2F__wildcardpermissions HTTP/1.1 200 55 - 0.475 ms
realm_1  | info: 127.0.0.1 - GET /realms/files/%2F__password HTTP/1.1 200 44 - 0.507 ms
realm_1  | info: Realm Object Server has started and is listening on http://0.0.0.0:9080
realm_1  | Your server is started  0.0.0.0:9080
realm_1  | info: sync-client: Connection[5]: Connected to endpoint '0.0.0.0:9080' (from '127.0.0.1:43150')
realm_1  | info: sync-client: Connection[6]: Connected to endpoint '0.0.0.0:9080' (from '127.0.0.1:43154')
realm_1  | info: sync-client: Connection[7]: Connected to endpoint '127.0.0.1:43921' (from '127.0.0.1:59020')
realm_1  | error: Internal server error: TypeError: Cannot read property 'reason' of undefined
realm_1  |     at CloudkitAuthProvider.<anonymous> (/realm/server/node_modules/realm-object-server/dist/auth/cloudkit/CloudkitAuthProvider.js:48:33)
realm_1  |     at throw (native)
realm_1  |     at rejected (/realm/server/node_modules/realm-object-server/dist/auth/cloudkit/CloudkitAuthProvider.js:5:65)
realm_1  |     at process._tickCallback (internal/process/next_tick.js:109:7)
  </code>
</details>

**Comment by molind** [comment]
P.S. seems your internal CloudKit public key bundled inside `node_modules/realm-object-server/dist/auth/cloudkit/fixtures`

**Comment by molind** [comment]
Exception returned to CloudkitAuthProvider signedRequest:

```
realm_1  | info: 134.17.141.169 - POST /auth HTTP/1.1 200 836 - 6.007 ms
realm_1  | error: Internal server error: TypeError: First argument must be a string or Buffer
realm_1  |     at ClientRequest.OutgoingMessage.end (_http_outgoing.js:557:11)
realm_1  |     at Request._end (/realm/server/node_modules/superagent/lib/node/index.js:970:9)
realm_1  |     at Request.end (/realm/server/node_modules/superagent/lib/node/index.js:751:15)
realm_1  |     at /realm/server/node_modules/superagent/lib/request-base.js:196:12
realm_1  |     at Request.then (/realm/server/node_modules/superagent/lib/request-base.js:195:31)
realm_1  |     at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by molind** [comment]
reproduced on ROS 2.0.6

**Comment by bigfish24** [comment]
@molind I am looking into this now

**Comment by molind** [comment]
@bigfish24 Thanks!

BTW could you add import paths for  
`import { CloudkitAuthProvider } from "../node_modules/realm-object-server/dist/auth/cloudkit/CloudkitAuthProvider"`
into documentation. It's was quite difficult to guess it from unexperienced TypeScript developer.
