### ISSUE TITLE
Feature : Realm Studio : Save Connection

### ISSUE THREAD

**Issue by kgiroux** [realm/realm-object-server#283]
## Goals

Save the connection params to the realm in Realm Studio

## Expected Results

Saving the params, users, and password for an easy connection

## Actual Results

Nothing, 

- Realm Object Server Version: 2.0

**Comment by bmunkholm** [comment]
@kgiroux Sure - absolutely. That's already on the backlog to get made together with a list of recent connections/files opened.

**Comment by kgiroux** [comment]
I try to found the back log, but without success. Can you give me a link. It will be usefull for me to not create duplicate

**Comment by bigfish24** [comment]
This feature has been added awhile back, sorry for not updating!
