### ISSUE TITLE
HTTP: Failed to switch protocols (response status = 404)

### ISSUE THREAD

**Issue by remirobert** [realm/realm-object-server#284]
Bugs:

I am using a digital ocean droplet for my realm server instance.
On my iOS app I got that error : 

```
2017-10-24 10:35:14.743559+0200 App[68284:10158128] Sync: Connection[1]: WebSocket::handle_http_response_received()
2017-10-24 10:35:14.743829+0200 App[68284:10158128] Sync: Connection[1]: HTTP: Failed to switch protocols (response status = 404)
2017-10-24 10:35:14.744255+0200 App[68284:10158128] Sync: Connection[1]: Connection closed due to error
2017-10-24 10:35:14.744930+0200 App[68284:10158128] Sync: Connection[1]: Reconnecting in 3088421 milliseconds
```

I can login and create a user from this app. But impossible to push data.
I can connect with the realm dashboard just fine.
For now my server is not using https. 

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? Ubuntu 17.04, ros version 2.0.4
- Client SDK Version: ? 2.10.0
- Client OS & Version: ?

**Comment by bigfish24** [comment]
What version of the server are you using?

**Comment by remirobert** [comment]
I am using the version 2.0.4

**Comment by bigfish24** [comment]
@remirobert the 2.0 version of the server requires 3.0 of realm-cocoa to connect to it. I will make a note to call this out stronger in the documentation.

**Comment by ryanherman** [comment]
I'm having the exact same issue with Xamarin.

**Comment by bigfish24** [comment]
@ryanherman did you follow these directions as well with the upgrade? https://realm.io/docs/xamarin/latest/#migrating-from-realm-object-server-1-to-2

**Comment by ryanherman** [comment]
I was about to come back to erase my message because...  I was trying to convert my PCL to .NETStandard and was having major problems with Realm 2.0, so downgraded to 1.6.  Well the server was on 2.0 and I was on 1.6.  Now that I've gotten that issue correct, I'm working on the upgrade.

Thank you!

**Comment by bigfish24** [comment]
Not sure but will ping our .Net team.

**Comment by ryanherman** [comment]
Works perfect on iOS

**Comment by nirinchev** [comment]
I don't see an obvious explanation for getting this error. Few things I could suggest:
- Clearing bin, obj, packages, *and* the [global .nuget package cache](http://lastexitcode.com/projects/NuGet/FileLocations/).
- Checking if the Xamarin linker is turned on and temporarily disabling it.

If none of those work out for you, feel free to open an issue at the [.NET repo](http://github.com/realm/realm-dotnet) and we'll investigate further.

**Comment by ryanherman** [comment]
Clearing out the bin, obj worked.  Thank you.
