### ISSUE TITLE
RealmFile.syncLabel must be of type 'string', got 'null' when try migrating to 2.0

### ISSUE THREAD

**Issue by AlekseyKolosovskiy** [realm/realm-object-server#287]
We are trying to migrate our data from ROS 1 to 2, and get this error:

info: copied user realm /mnt/realm/old/realm/realm-object-server/object-server/root_dir/0/user_data/684894a6a6ed2271ff0039dee185795c/main.realm -> /mnt/realm/organicfit/sync/user_data/684894a6a6ed2271ff0039dee185795c/main.realm
info: realm: /61a2717d98a3e9caa1bb0946f63f8deb/main
info: copied user realm /mnt/realm/old/realm/realm-object-server/object-server/root_dir/0/user_data/61a2717d98a3e9caa1bb0946f63f8deb/main.realm -> /mnt/realm/organicfit/sync/user_data/61a2717d98a3e9caa1bb0946f63f8deb/main.realm
info: realm: /e4fe7d9fe7da00ba6444ded7fdf161a4/main
info: copied user realm /mnt/realm/old/realm/realm-object-server/object-server/root_dir/0/user_data/e4fe7d9fe7da00ba6444ded7fdf161a4/main.realm -> /mnt/realm/organicfit/sync/user_data/e4fe7d9fe7da00ba6444ded7fdf161a4/main.realm
info: realm: /93e783961ad5a3a5ac912b3c29d84fa3/main
error: (node:13319) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: RealmFile.syncLabel must be of type 'string', got 'null' (null)

After this migration stopped.

**Comment by kvap** [comment]
Thank you for reporting this. We are going to fix this bug shortly. Meanwhile, you can work around that by doing the following:
1. Modify the file `/mnt/realm/old/realm/realm-object-server/object-server/root_dir/__admin.json`. All elements in `realms` array there should contain `"cluster_node_id": "0"`. This can be done with [jq](https://stedolan.github.io/jq/), the commands needed are:

   ```bash
   export OLDROOT=/mnt/realm/old/realm/realm-object-server/object-server/root_dir
   export NEWROOT=/mnt/realm/organicfit/
   cd "$OLDROOT"
   mv __admin.json __admin.json.bad
   jq '.realms[].cluster_node_id |= "0"' __admin.json.bad > __admin.json
   ```

2. Restart the second part of migration (import into ROS2), skipping the export from ROS1.
   ```bash
   npm ls -g realm-object-server # this will tell you where ROS is installed
   node PATH_TO_ROS/node_modules/realm-object-server/dist/migration/to2.js --from "$OLDROOT" --to "$NEWROOT" --copyrealms
   ```
