### ISSUE TITLE
Crash during logging

### ISSUE THREAD

**Issue by kspangsege** [realm/realm-object-server#289]
The following crash was reported by a user on StackOverflow ([link](https://stackoverflow.com/questions/47006890/what-would-cause-ros-to-crash-with-this-error-realm-exited-with-code-134)):

```
realm    | read configuration from /etc/realm/configuration.yml.
realm    | FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
realm    |  1: node::Abort() [/usr/lib/realm-object-server-developer/node/bin/node]
realm    |  2: 0x109bf8c [/usr/lib/realm-object-server-developer/node/bin/node]
realm    |  3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/lib/realm-object-server-developer/node/bin/node]
realm    |  4: RealmLoggerQueue::log_uv_callback() [/usr/lib/nodejs/realm-object-server-developer/node_modules/realm-sync-server/compiled/linux-x64/node-v48/realm-sync-server.node]
realm    |  5: 0x131d53b [/usr/lib/realm-object-server-developer/node/bin/node]
realm    |  6: 0x131d613 [/usr/lib/realm-object-server-developer/node/bin/node]
realm    |  7: 0x132dda8 [/usr/lib/realm-object-server-developer/node/bin/node]
realm    |  8: uv_run [/usr/lib/realm-object-server-developer/node/bin/node]
realm    |  9: node::Start(int, char**) [/usr/lib/realm-object-server-developer/node/bin/node]
realm    | 10: __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
realm    | 11: 0x7b8dad [/usr/lib/realm-object-server-developer/node/bin/node]
realm    | Aborted
realm exited with code 134
```

As far as I can see, the crash happens due to invalid use of `v8::ToLocalChecked()` during the execution of `RealmLoggerQueue::log_uv_callback()`.

**Comment by kspangsege** [comment]
I have asked the user whether he/she can share the particular Realm file that caused the shown crash.

**Comment by pbcaus** [comment]
The Realm file has been sent to help@realm.io.

**Comment by kspangsege** [comment]
I was unable to reproduce the crash using the JS binding on the client side in place of Swift.

More specifically, I

- used ROS 1.8.3 on server side,
- used Realm JS 1.13.0 on the client side, and
- copied the objects in the provided Realm into a new synchronized Realm using the script shown below.

This completed successfully, i.e., no crash.

Script to copy object into synchronized Realm:

```js
const Realm = require('realm');
const fs = require('fs');
const path = require('path');

// Unlock Professional Edition APIs
Realm.Sync.setFeatureToken(fs.readFileSync(path.join(__dirname, './enterprise-token.jwt'), 'utf-8'));

const source_realm_path = './source.realm'; // path on disk

function copyObject(obj, objSchema, targetRealm) {
    const copy = {};
    for (var key in objSchema.properties) {
        const prop = objSchema.properties[key];
        if (prop.type == 'list') {
            const propObjSchema = targetRealm.schema.find((s) => s.name == prop.objectType)
            copy[key] = obj[key].map((obj) => copyObject(obj, propObjSchema, targetRealm))
        }
        else if (prop.type == 'object') {
            const propObjSchema = targetRealm.schema.find((s) => s.name == prop.objectType)
            copy[key] = obj[key] ? copyObject(obj[key], propObjSchema, targetRealm) : obj[key];
        }
        else {
            copy[key] = obj[key];
        }
    }
    return copy;
}

function copyRealm(user, local_realm_path, remote_realm_url) {
    // Open the local realm
    const source_realm =  new Realm({
        path:     local_realm_path,
        readOnly: true,
    });
    const source_schema = source_realm.schema;

    // Create the new realm (with same schema as the source)
    const target_realm = new Realm({
        sync: {
            user: user,
            url:  remote_realm_url,
        },
        schema: source_schema,
    });

    // Copy all objects but ignore links for now
    target_realm.schema.forEach((objSchema) => {
        console.log("Copying objects:", objSchema['name']);
        const allObjects = source_realm.objects(objSchema['name']);
        target_realm.write(() => {
            allObjects.forEach(obj => {
                // Add this object to the target realm
                target_realm.create(objSchema.name, copyObject(obj, objSchema, target_realm), true);
            });
        });
    });
}

const remote_realm_url = 'realm://localhost:9080/~/foo';

Realm.Sync.User.login('http://localhost:9080', 'test', 'test').then(user => {
    copyRealm(user, source_realm_path, remote_realm_url);
    console.log("Done");
});
```

cc @kvap

**Comment by kspangsege** [comment]
Note, a link to the uploaded Realm (uploaded by @pbcaus to *help@realm.io*) is posted [here](https://realmio.slack.com/archives/C3E9D49GU/p1510066608000551).

**Comment by pbcaus** [comment]
The crash does not occur during the transfer: my transfers using Swift will always complete.  The crash happens when I use Realm Browser (2.1.12) to access the Realm on ROS after the transfer.

**Comment by kspangsege** [comment]
Alright. Thanks for the clarification @pbcaus .

**Comment by pbcaus** [comment]
As an additional thought: I am only copying objects from the local source to the server that have a primary key (which most do).  The logic behind this is that the Objects in our Realm without primary keys already "logically belong" to another Object that has a primary key, so they would be copied when the parent object was copied. I also thought it was a way of preventing duplicates occurring in the target Realm: one copy created during the "parent" copy and one copy created from when the Object's class is picked up from the Realm schema.  I wouldn't think that this causes the crash, as my other two Realms work correctly using this technique, but just in case it has a bearing. @kspangsege

**Comment by kspangsege** [comment]
Hi @pbcaus . We finally figured out what is causing this crash. It is due to excessive size of a log message (302MB in this case).

The log message in question is a hex dump of a large changeset. Unfortunately, this message is generated because ROS logs at `trace` level (at least be default).

I will let you know if there is a way to change the log level in question.

**Comment by kspangsege** [comment]
This issue is now addressed for ROS 2 and onward by clamping the size of logged hex dumps to 1024 bytes (https://github.com/realm/realm-sync/pull/1820).

@pbcaus I''' get back to you on whether there is a workaround for ROS 1.

**Comment by bmunkholm** [comment]
@pbcaus Is it possible for you to upgrade to 2.0? Are you in production? If not, then you definitely should.

**Comment by pbcaus** [comment]
@kspangsege @bmunkholm 
We are not yet in production, but we were just about to kick off Alpha trials when this problem emerged, so we're not keen to change at this point.  Maybe between Alpha and Beta trials we could make the move, but at the moment, we just want to focus on the business aspects of the software so we can get to market soon. If the Alpha trials run into this problem, then we will have no choice but to make the move, but given we are already slipping on our schedule, we need to keep moving forward at this stage.

**Comment by bmunkholm** [comment]
@pbcaus Fully get that. It's just even more important for you to know that 2.0 is by definition not fully backwards compatible with 1.0, so there is a migration step you have to make on the server, and also handle migration in the app. There is a bunch of things fixed in 2.0, so I can only highly recommend moving to that asap as a number of bugs has been fixed and performance is much better in 2.0. You can take a peek at the migration guide to judge for yourself: https://realm.io/docs/realm-object-server/latest/#upgrading
But again, I highly recommend you to use 2.0 as that is what is being actively developed.

**Comment by pbcaus** [comment]
@bmunkholm 
Ok - we will look into it to see how it affects our schedules.  We'll get someone to look at total effort and schedule it in.

**Comment by kvap** [comment]
> workaround for ROS 1

@pbcaus to workaround this in ROS1 you can edit the file `node_modules/realm-object-server-developer/node_modules/ros-service-sync/dist/SyncService.js` and set `level: "info"` or lower on line 36. I don't know exactly where this `node_modules` is located, it depends on how you installed ROS.

**Comment by pbcaus** [comment]
@kvap 
Thanks, found it and have made the change.  We will let you know how it goes.  
Thanks.
