### ISSUE TITLE
Swift 3.2.2 use of swift 4.0 RealmSwift won't compile with error "

### ISSUE THREAD

**Issue by CoreySmith1200** [realm/realm-object-server#291]
## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by CoreySmith1200** [comment]
Module compiled with Swift 4.0 cannot be imported in Swift 3.2.2:

**Comment by bdash** [comment]
I'm not sure what version of Realm you were attempting to use, or how you were attempting to integrate Realm into your app (this is information that's requested in the new issue template). That said, [Realm Swift v3.0.2](https://github.com/realm/realm-cocoa/releases/tag/v3.0.2) and newer contain prebuilt binaries for Xcode 9.1 which will likely address your problem.
