### ISSUE TITLE
ROS2 custom auth provider, setting custom uid not working

### ISSUE THREAD

**Issue by ashhanai** [realm/realm-object-server#292]
## Goals

Setting custom unique user id while creating new realm user in custom auth provider with `createOrUpdateUser` method.

## Expected Results

Newly created user have the custom user id.

## Actual Results

Newly created user have generated user id. Result is same as passing null into the `createOrUpdateUser` method.

## Code Sample

`const user = this.service.createOrUpdateUser(uid, "myAuth", false, uid);`

## Version of Realm and Tooling

- Realm Object Server Version: 2.0.13
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: MacOS

**Comment by bigfish24** [comment]
Thanks for filing, we are looking into this!

**Comment by ashhanai** [comment]
I found a workaround until a fix will be released. Use curly brackets `{}` as a 4th parameter in `createOrUpdateUser` method and custom uid as a 5th. 

`const user = this.service.createOrUpdateUser(uid, "myAuth", false, {}, uid);`

In method decralation is 4th parameter used for metadata list and 5th for uid.

**Comment by cbush** [comment]
Not sure what's to be done for Docs. Has this issue been resolved?

**Comment by ianpward** [comment]
closing - this is the definition of the API spec: 
https://realm.io/docs/realm-object-server/latest/api/ros/classes/authservice.html#createorupdateuser
