### ISSUE TITLE
ROS (v2.0.13) fails to start (https)

### ISSUE THREAD

**Issue by NaokiKojima** [realm/realm-object-server#293]
## Goals
Execution at npm start https succeeded.

## Issue Description
Execution at npm start http succeeded
But changing to https failed.
Refer to the following URL and set the necessary items.

https://realm.io/docs/realm-object-server/latest/#cli

Since the error content is Logger of undefined, https setting bug?

## Code Sample
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const realm_object_server_1 = require("realm-object-server");
const path = require("path");
const server = new realm_object_server_1.BasicServer();
server.start({
    dataPath: path.join(__dirname, '../data'),
    https: true,
    httpsKeyPath: '/etc/letsencrypt/live/{yourdomain.com}/privkey.pem',
    httpsCertChainPath: '/etc/letsencrypt/live/{yourdomain..com}/cert.pem'
})
    .then(() => {
    console.log(`Your server is started `, server.address);
})
    .catch(err => {
    console.error(`There was an error starting your file`);
});
```

## Version of Realm and Tooling

- Realm Object Server Version:  2.0.13
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version:  CentOs 7.4
- Node v8.9.0 (npm v5.5.1)

## Logs
> ```
> There was an error starting your file
> Detected an unhandled promise rejection at:  Promise {
>   <rejected> TypeError: Cannot read property 'logger' of undefined
>     at BasicServer.get logger [as logger] (/home/nao/test/node_modules/realm-object-server/dist/Server.js:65:35)
>     at BasicServer.<anonymous> (/home/nao/test/node_modules/realm-object-server/dist/BasicServer.js:136:22)
>     at Generator.next (<anonymous>)
>     at /home/nao/test/node_modules/realm-object-server/dist/BasicServer.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (/home/nao/test/node_modules/realm-object-server/dist/BasicServer.js:3:12)
>     at process.on (/home/nao/test/node_modules/realm-object-server/dist/BasicServer.js:135:40)
>     at emitNone (events.js:106:13)
>     at process.emit (events.js:208:7)
>     at Signal.wrap.onsignal (internal/process.js:208:44) } , reason:  TypeError: Cannot read property 'logger' of undefined
>     at BasicServer.get logger [as logger] (/home/nao/test/node_modules/realm-object-server/dist/Server.js:65:35)
>     at BasicServer.<anonymous> (/home/nao/test/node_modules/realm-object-server/dist/BasicServer.js:136:22)
>     at Generator.next (<anonymous>)
>     at /home/nao/test/node_modules/realm-object-server/dist/BasicServer.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (/home/nao/test/node_modules/realm-object-server/dist/BasicServer.js:3:12)
>     at process.on (/home/nao/test/node_modules/realm-object-server/dist/BasicServer.js:135:40)
>     at emitNone (events.js:106:13)
>     at process.emit (events.js:208:7)
>     at Signal.wrap.onsignal (internal/process.js:208:44)
> ```

**Comment by bigfish24** [comment]
Thanks for filing, we are looking into this!

**Comment by NaokiKojima** [comment]
@bigfish24 
I'm sorry.
I withdraw the issue.
It was because the executing user did not have permission to the certificate directory.
Permissions on the certificate directory resolved.
Another problem occurred in Realm Studio and Realm Browser that data can not be referenced.
