### ISSUE TITLE
Realm Studio connection via HTTPS fails to display Realm and User information

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [realm/realm-object-server#294]
## Goals

View Realm and User information in Realm Studio - connected to ROS via HTTPS

## Expected Results

Clicking on the Realm or User tab would display appropriate data.

## Actual Results

The "loading" indicator displays, continually - when viewing the Realm and User tabs.  When viewing the Log tabs - log data displays.

If I connect to ROS using HTTP - the Realm and User tabs display data as expected.

## Steps to Reproduce

Launch Realm Studio and connect to ROS v2.1.0 via HTTPS.

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - Developer
- Server OS & Version: ? Ubuntu 16.04
- Realm Studio v1.5
- ROS v2.1.0

**Comment by bigfish24** [comment]
Thanks for filing, will have this looked at ASAP.

**Comment by kraenhansen** [comment]
@ianbradbury-bizzibody can I ask - what kind of https certificates are you using? Self-signed or signed by a trusted CA?

**Comment by ianbradbury-bizzibody** [comment]
Letsencrypt.  I just tested the cert and all appears good.

**Comment by kraenhansen** [comment]
Are you running both Studio and ROS on the same Ubuntu 16.04 machine?

**Comment by kraenhansen** [comment]
I was able to reproduce this.

**Comment by kraenhansen** [comment]
A fix for this will be released as Realm Studio v1.6.1 in a few hours.

**Comment by kraenhansen** [comment]
@ianbradbury-bizzibody please verify and reopen if this didn't fix the issue.

**Comment by ianbradbury-bizzibody** [comment]
Thanks.  Sorry for the delay - other things got in the way.  The new release works perfectly.  Thanks for your efforts.

**Comment by kraenhansen** [comment]
Great! I'm glad to hear that :)

**Comment by jaisontj** [comment]
Hi, I seem to be having the same issue. Except my ros is running behind a gateway and I have not enabled https on the ros. The server is running at https://ros.critique72.hasura-app.io/, but when I try to connect to it using Realm Studio nothing loads (just a loading indicator is shown)

Note: I am able to login to the server using realm studio, just not able to view the realms.
