### ISSUE TITLE
No data on ROS

### ISSUE THREAD

**Issue by seferdemir** [realm/realm-object-server#296]
I removed ROS after Error:Failed to resolve ':::9080'. I reinstalled ROS v1.8.3 and copied files to /var/lib/realm/object-server/0/user_data. Users can login but no data. How can i resolve it?

**Comment by bigfish24** [comment]
Are you trying to migrate to 2.0?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seferdemir** [comment]
Thank you for interest. No, but can I migrate while preserving data? Current version is v1.8.3, but previous data does not appear.

**Comment by bigfish24** [comment]
Have you read the migration docs: https://realm.io/docs/realm-object-server/latest/#upgrading which will help copy and convert the data for 2.0. If the app is deployed you have to do a couple updates to make it seamless for your users, as described in the doc. Each SDK provides a callback to manually copy data from the client 1.x Realm to 2.0 such as https://realm.io/docs/swift/latest/#migrating-from-realm-object-server-1-to-20

As for 1.8.3 did you make sure the configuration.yml has the data path correct?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seferdemir** [comment]
Yes I have read. I don't use Swift. How can i do it for Java? Where is the /srv/old-root directory?

**Comment by bmunkholm** [comment]
@seferdemir Did you get further on this? Did you check the relevant section in the Java docs? https://realm.io/docs/java/latest/#migrating-from-realm-object-server-1-to-2?

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
