### ISSUE TITLE
realm-backup command not found in Realm Object Server 2.0 

### ISSUE THREAD

**Issue by toanz** [realm/realm-object-server#298]
I want to use manual backup in [Document](https://realm.io/docs/realm-object-server/latest/#cli) but this command is not exits 

i already try with : ros --help , but it do not have backup command also 

How can we do manual backup with Realm Object Server 2.0 ?

**Comment by hyling** [comment]
@bigfish24 Do you have comments on this?  I wouldn't considering deploying ROS 2.0 until I knew I could backup the sever.  Thanks!

**Comment by bigfish24** [comment]
Yeah we are working to fix the issue. Should be ready early this coming week.

**Comment by hyling** [comment]
Awesome, thanks for the reply!

**Comment by sipersso** [comment]
Any updates on this?

**Comment by morten-krogh** [comment]
Type 

realm-backup

at the command line in your project directory.

The realm-backup script is located at

node_modules/realm-object-server/node_modules/realm-sync-server/bin/realm-backup

It calls an architecture dependent binary called realm-backup as well.

By mistake, we did not include realm-backup in the first versions of realm-object-server 2.0

realm-backup is present in the newest realm-object-server versions.

**Comment by bigfish24** [comment]
This is fixed in ROS 2.0 where the backup command is in the CLI, see more in the docs: https://docs.realm.io/platform/manage/backup
