### ISSUE TITLE
How to connect cloud with nodejs

### ISSUE THREAD

**Issue by vinothmoorthkumar** [realm/realm-object-server#301]
When i m inserting data using nodej the data only storing in project folder... Please anybody tell me how to connect could with my nodejs. 

Then i m facing this error:(node:24525) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Sync feature
not available

**Comment by bigfish24** [comment]
Can you supply more information such as a code sample and error you are getting?

**Comment by TheNoim** [comment]
The sync feature is only available in the enterprise version. I think they should add an option for private student projects to also access the sync feature.

**Comment by mgeerling** [comment]
Just an update in case anyone else is receiving `Error: Sync feature not available`

We have changed the way that we handle tokening.  You will want to upgrade to a version of realm-js newer than 2.3.0, and you should no longer receive this error.
