### ISSUE TITLE
Can't build ROS 2.0 when using middleware

### ISSUE THREAD

**Issue by Damnum** [realm/realm-object-server#304]
## Goals

Build ROS via NPM using `npm run-script build`

My `./src/index.ts` looks like this:

```
import * as cors from 'cors'
import { Server } from 'realm-object-server'
import * as path from 'path'

const server = new Server()
console.log("Server Ling", server)
server.useMiddleware(cors())
...
```

## Expected Results

Build is successful.

## Actual Results

Build throws error:
`error TS2339: Property 'useMiddleware' does not exist on type 'Server'`

## Steps to Reproduce
My setup follows the steps provided in the docs: https://realm.io/docs/realm-object-server/latest/#custom-middlewares

Why does `Server.useMiddleware` not exist?

## Version of Realm and Tooling

- Realm Object Server Version: 2.0.13
- Flavor:
  - [ ] Developer
- Server OS & Version: Ubuntu 16.04
- TypeScript Version: 2.5.3
- NPM Version: 5.5.1
- Node Version: 8.9.0

**Comment by mbalex99** [comment]
We made a minor API change about the `useMiddlewares` now it is a start param called `middlewares`

```typescript
import { BasicServer } from 'realm-object-server'
import * as path from 'path'
import * as cors from 'cors'

const server = new BasicServer()

server.start({
        // This is the location where ROS will store its runtime data
        dataPath: path.join(__dirname, '../data')
        middlewares: [cors()]
    })
    .then(() => {
        console.log(`Realm Object Server was started on ${server.address}`)
    })
    .catch(err => {
        console.error(`Error starting Realm Object Server: ${err.message}`)
    })
```

**Comment by Damnum** [comment]
Ok thanks, that works now.

**Comment by mbalex99** [comment]
Glad to have helped

**Comment by TariqTawalbeh** [comment]
can I get any synced data from the middleware and put it on anywhere I want ?
