### ISSUE TITLE
Use BacklinksCount in queries

### ISSUE THREAD

**Issue by nielsenko** [realm/realm-object-server#307]
## Goals

This is a feature request to be able to use BacklinksCount in queries. Currently the query engine complains it is not a directly persisted property.

## Expected Results

Allow construction such as:

`
realm.RemoveRange(self.All<T>().Where(i => i.BacklinksCount == 0));
`

## Actual Results

Today I need to do:

`
var die = realm.All<T>().AsEnumerable().Where(i => i.BacklinksCount == 0).ToList();
foreach (var item in die) realm.Remove(item);
`

Which rubs me the wrong way

## Version of Realm and Tooling

Any version after Realm-2.0.0, but I'm using Realm-2.1.0-alpha-345

**Comment by nirinchev** [comment]
Issue moved to [realm/realm-dotnet #1646](https://github.com/realm/realm-dotnet/issues/1646) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nielsenko** [comment]
Ups, sorry for posting under ROS
