### ISSUE TITLE
Upgrade ROS 1.0 to 2.0 from AWS EC2 instance.

### ISSUE THREAD

**Issue by FreudGit** [realm/realm-object-server#308]
Having a ROS 1.0 installed from amazon EC2 public AMI (see https://realm.io/docs/get-started/installation/deployment/#deploying-the-realm-object-server)

I've followed your upgrade steps.

When I run "ros migrate ..."  here are the exact result:
 ros migrate --from /var/lib/realm/object-server --to /var/lib/realm/object-server-v2/ --copyrealms
info: will export /var/lib/realm/object-server/internal_data/auth.realm -> /var/lib/realm/object-server/__admin.json
error: (node:31946) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unable to open a realm at path ‘/var/lib/realm/object-server/internal_data/auth.realm’. Please use a path where your app has read permissions.
 

From slack, get reply from user that confirm that she have similar problem.  Look like admin.json was installed on another folder than the expected one. (not in /var/lib/realm/object-server/__admin.json)

**Comment by bigfish24** [comment]
Thanks for reporting, we are looking into this.

**Comment by kvap** [comment]
@FreudGit which version of ROS2 is it? Looks like it did not create `__admin.json` because it failed to open `auth.realm` earlier.

**Comment by FreudGit** [comment]
@kvap 2.0.21. (you can easily catch me on #general channel of Slack (Realm))

**Comment by ianpward** [comment]
@FreudGit Can you please post all the commands you followed that led up to this error. Would also need to know the user you are running the commands with and version of node/npm please.

**Comment by FreudGit** [comment]
node -v  =  v8.9.0
npm -v = 3.8.3

About the steps, i've followed the steps here:
https://realm.io/docs/realm-object-server/latest/#upgrading

1- Installed pre-requisite:
sudo apt-get update
sudo apt-get install build-essential libssl-dev
sudo apt-get install python
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash

// Force current session to know changes or logout and log back in
source ~/.profile
nvm install --lts
npm install -g node-gyp

2- run npm install -g realm-object-server

**Comment by ianpward** [comment]
What about the migration steps? We also need the exact user you ran all the commands with

**Comment by FreudGit** [comment]
Migration:
ros migrate --from /var/lib/realm/object-server --to /var/lib/realm/object-server-v2/ --copyrealms

User:
main user\administrator.

**Comment by ianpward** [comment]
@FreudGit Thanks - can you list all files in each folder `object-server` and `object-server-v2` with permissions and ownership?

Judging from the slack messages:
https://realm-public.slack.com/archives/C03V755FS/p1511012231000021

My best guess is that you installed npm, nvm, or ros with different linux user and then attempted to run ros migrate with a user that did not have permissions. You should not need to chmod anything if the user is consistent. Can you please uninstall everything and then re-install and re-run the migration?

If you run into the same issue please post the exact commands with user for each step, for example:

`[centos@data-adapter-server ~]# sudo npm install realm`

**Comment by kvap** [comment]
@FreudGit make sure that you (the user running `ros migrate`) have read-write access to everything inside `/var/lib/realm/object-server`.

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
