### ISSUE TITLE
different installation instructions

### ISSUE THREAD

**Issue by nsnick** [realm/realm-object-server#309]
Why are there totally different installation instructions in these two links?
https://realm.io/docs/get-started/installation/deployment/
https://realm.io/docs/realm-object-server/latest/#going-into-production

The first link works and the second one gives 
Sync: Connection[1]: HTTP: Failed to switch protocols (response status = 404)

**Comment by bigfish24** [comment]
The first are old docs, for v1. Sorry that they are not properly documented as such. Please follow the second. That error likely means your client is not v2 compatible.

**Comment by nsnick** [comment]
Thanks.  You are correct.
