### ISSUE TITLE
How can I upgrade an existing ROS AMI?

### ISSUE THREAD

**Issue by jcrzry** [realm/realm-object-server#312]
When connected to the AWS instance, I cannot find any reference to the current ROS. There is nothing within the /srv directory. 
Any help would be appreciated!

**Comment by morten-krogh** [comment]
Sorry for the late reply.
We do not support ROS AMIs since the upgrade to ROS 2.0

You can install ROS as explained here

https://realm.io/docs/get-started/installation/developer-edition/
