### ISSUE TITLE
Ability to delete ROS user programmatically.

### ISSUE THREAD

**Issue by morteg** [realm/realm-object-server#315]
I think, that Realm users should be available to delete their account from ROS, but this feature is only available in Realm Studio.

Now I can't implement "Delete Account" feature in my app, I can just wipe out user data, but the account will be available and the user couldn't create new with the same credentials.

**Comment by morten-krogh** [comment]
@morteg 
There is a HTTP API to delete a user. Realm studio uses that HTTP request.
We have not documented it however. We will do that.

**Comment by morteg** [comment]
@morten-krogh 
So, am I available to delete a user account from my iOS app via HTTP request to my cloud-deployed ROS ?

**Comment by morten-krogh** [comment]
@morteg 
Yes, but you need permission to do that. You cannot delete anyone.

I have opened an issue that we need to document this API.

https://github.com/realm/realm-object-server/issues/326

**Comment by morteg** [comment]
@morten-krogh 
Thanks.
To use this request I need to be admin user, am I ? We can't add admin-user credentials to out app source code, because of security. Can we do such functionality in ROS service (https://realm.io/docs/realm-object-server/latest#extending-functionality)?

**Comment by morten-krogh** [comment]
Yes, there is a security issue with using an admin user.
The user can delete itself. Would that be good enough for you?

**Comment by rubengarciam** [comment]
+1 Looking forward to this. Kind of mandatory to allow users to delete their data/account from the backend server

**Comment by nirinchev** [comment]
The API call is:
```
DELETE http://my-ros-instance:9080/auth/user/:user_id
```

where `:user_id` is the id of the user in ROS. For example, if I have a user with Id: `12345`, I could execute:

```
curl -X "DELETE" http://my-ros-instance:9080/auth/user/12345
```

to delete them. We're working on providing a comprehensive documentation of the HTTP API, but wanted to post this here in case any of you are blocked by this.

**Comment by morteg** [comment]
@morten-krogh , @nirinchev 
Thank you very much! 
That is exactly what I need.

**Comment by nirinchev** [comment]
Forgot to mention that you need to set the `authorization` header with the user's refresh token:

```
authorization: eyJhcHBfaWQiOiJ...
```

How to obtain the user's refresh token depends on the client-side SDK you're using. For example:
- Cocoa has a private property on the SyncUser class: [_refreshToken](https://github.com/realm/realm-cocoa/blob/v3.0.2/Realm/RLMSyncUser_Private.hpp#L68)
- Java can serialize a SyncUser to json by calling [.toJson](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/objectServer/java/io/realm/SyncUser.java#L475) and the token is stored in the `userToken` property in the json string.
- .NET exposes [User.RefreshToken](https://realm.io/docs/dotnet/latest/api/reference/Realms.Sync.User.html#Realms_Sync_User_RefreshToken).
- JS exposes [SyncUser.token](https://realm.io/docs/javascript/2.1.0/api/Realm.Sync.User.html#token).

I'll close this as the Http API should allow deleting the user and we'll keep tracking the documentation improvement issue in #326.

**Comment by i-schuetz** [comment]
Is it planned to add this call to the (non http) Realm api at some point? Seems like something that should be there, together with login, register, etc.

**Comment by i-schuetz** [comment]
Are there plans to add this to the library api? Seems to fit together with login, register, etc.

@nirinchev
You say "How to obtain the user's refresh token (...): Cocoa has a private property on the SyncUser class: _refreshToken" how am I supposed to use it, if it's private? Am I missing something? 🤔

**Comment by nirinchev** [comment]
I'm not super experienced with cocoa development, but can't you simply include the private headers in your project?

Yes, there are plans to expose this API in the SDKs at some point.

**Comment by i-schuetz** [comment]
What do you mean with include the private headers? It's a private variable in an implementation file (RLMSyncUser.mm) and it's not possible to access it from outside. Maybe I'm missing a hack to do this. Using Swift. Any ideas? Also, a few months have passed and it's still not possible to do this using the SDK. Is it planned soon? Or do I have to tell users to send me an email to delete them manually?

**Comment by sagarshirbhate** [comment]
Hi guys ,
Would you like to share full request how to delete a user from realm?
I tried using 
`DELETE  http://my-ros-instance:9080/auth/user/:user_id`
also added below key into headers of request.
`authorization: ---- refresh Token of sync user----`

but it says,
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot DELETE /auth/user/</pre>
    </body>
</html>
```


Help will be appreciated !

**Comment by nirinchev** [comment]
Looks like your `userId` parameter was missing because the route appears to have resolved to `/auth/user/` with nothing after that.

**Comment by sagarshirbhate** [comment]
Hello @nirinchev  I tried ,
URL :  `https://********ros****/auth/user/`
MethodType : ` Delete`
Headers : 
`{authorization:eyJhcHBfaWQiOiJjb20ubmluZWJ4Lm5pbmVieCIsImlkZW50aXR5IjoiNzZkYTg4NzIxNGFjNzA4MjgzMmUwMjA4N2FmMDg3YmEiLCJhY2Nlc3MiOlsicmVmcmVzaCJdLCJzYWx0IjoiNGI5ZWViNzAiLCJleHBpcmVzIjoxODY3MjEyNjc3LCJpc19hZG1pbiI6ZmFsc2UsImlzRW1haWxDb25maXJtZWQiOmZhbHNlfQ==:ak1lfUFDUbPE0T68i9bWkCLNwG1BbzlOKgQmRufwwqzhtaaxxAO3r6D3YnCbzvI6bHa4kPuPbKxwalzyJONPv6jIw0xZzQXd0fzcuUl5iS87iuDciniIpHR3XgLfdA+7KFFwfsB+V5ko6pVlv74aebUOVWAcSbdTcXFip9UrvjnDHJ4Ow8/Ut5sM6LbCTofC9h3HJutAi0q1jDPa3tni94+BgnEABMHQuP2zltnmKXao7IlQxWGuz6KuqYcFw9rNu8k69KWgyE85oqFJ+vsrOkAXyThiBQrfzf3jfLLjxTTpMdHiG3rCQKjUFxWZgRXgDNmsfgvKZ7IzyvTwLH/QFA==}`
Params:`{userId: 92ca78e95199f8cfc13ecf02a0c2f9df}`

Still Giving same error.
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot DELETE /auth/user/</pre>
    </body>
</html>
```

Would you like to share whole request by which it will be better.
Help will be appreciated !

**Comment by nirinchev** [comment]
I have done this in my comment here: https://github.com/realm/realm-object-server/issues/315#issuecomment-356267112

As I mentioned, you need the userId after the `auth/user` route in the URL. Namely, you need to modify your URL to `https://********ros****/auth/user/92ca78e95199f8cfc13ecf02a0c2f9df`.

**Comment by RayBrack** [comment]
For anyone looking for a .NET version;
```
var client = new HttpClient();
client.BaseAddress = new Uri($"{RealmInstance}");
client.DefaultRequestHeaders.TryAddWithoutValidation("authorization", user.RefreshToken);
HttpResponseMessage response = await client.DeleteAsync($"/auth/user/{user.Identity}");
