### ISSUE TITLE
ROS creates empty Realm when asked for an access token

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-server#316]
When an auth call is made asking to swap the refresh token for an access token with a path that points to a non-existent Realm, ROS will create an empty Realm before returning the token. This has been a source of confusion for users because, if they use the wrong URL for a sync configuration, they'll see the Realm in studio, but no data will ever be synced, see https://github.com/realm/realm-dotnet/issues/1654.

**Comment by bmunkholm** [comment]
Issue moved to [realm/realm-object-server-private #841](https://github.com/realm/realm-object-server-private/issues/841) via [**ZenHub**](https://www.zenhub.com/)
