### ISSUE TITLE
scientific notation - realm studio

### ISSUE THREAD

**Issue by jmparsons** [realm/realm-object-server#318]
I couldn't find a repository for Realm Studio, but the results in the ui differ from Realm Browser for number fields with small values showing to scientific notation instead of numbers.

**Comment by kraenhansen** [comment]
This is probably due to limitation in the JavaScripts representation of numbers. Could I get you to comment with a couple of examples of schema property definitions and numbers and what results you're expecting to work differently?

**Comment by bmunkholm** [comment]
@jmparsons Could you comment on above?

**Comment by jmparsons** [comment]
Yeah for the old realm you could write numerically 0.000000007 and it would
show that value versus the studio version shows number e+8^7. It’s a
JavaScript issue yes, so however the conversion was made on the old one to
show actual value would be a nice representation.

**Comment by astigsen** [comment]
If this is still an issue, please reopen in the Realm Studio repo: https://github.com/realm/realm-studio/
