### ISSUE TITLE
Feature: Realm Studio: Open realm file from command line

### ISSUE THREAD

**Issue by evgeny-sureev** [realm/realm-object-server#324]
## Goals

It would be nice to be able to open realm files from Finder or command line.

## Expected Results

Open my database in Realm Studio after double clicking on file in Finder or typing `open /Users/evgeny/Library/Developer/CoreSimulator/Devices/4056AA5C-0AC0-4258-BBE3-24BB5930EA60/data/Containers/Data/Application/C036C70B-CD4F-4514-BAEC-045B8B0179DD/Documents/default.realm` in Terminal.

**Comment by bigfish24** [comment]
The latest version 1.15 should work with this.

**Comment by evgeny-sureev** [comment]
No, it just opens and shows open file dialog.

**Comment by bigfish24** [comment]
Hmm we specifically added this feature, you have the latest version? I will retest on my end.

**Comment by evgeny-sureev** [comment]
Yes, latest version.

**Comment by bigfish24** [comment]
@evgeny-sureev my apologies, I misspoke in my original comment. We had merged the support but then had an issue on Windows/Linux so we reverted. The latest version 1.16.0 now has the ability to open a Realm when double-clicking. Please verify on your end, thanks!

**Comment by evgeny-sureev** [comment]
Thank you, all is working now.

**Comment by bigfish24** [comment]
👍

**Comment by maulik6994** [comment]
> Yes, latest version.
> 
> Realm Studio Version 1.15.0
> Mac OS X Version 10.13.2

Yes Its just open Dialog box
