### ISSUE TITLE
Realm

### ISSUE THREAD

**Issue by jasondp** [realm/realm-object-server#330]
java.lang.IllegalArgumentException: User is not part of the schema for this Realm
01-12 14:25:45.327 30017-30017/com.dayton.drone W/System.err:     at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:169)
01-12 14:25:55.864 30017-30017/com.dayton.drone W/System.err:     at io.realm.internal.modules.CompositeMediator.getSimpleClassNameImpl(CompositeMediator.java:87)
01-12 14:26:36.823 30017-30017/com.dayton.drone W/System.err:     at io.realm.internal.RealmProxyMediator.getSimpleClassName(RealmProxyMediator.java:79)
01-12 14:26:36.825 30017-30017/com.dayton.drone W/System.err:     at io.realm.RealmSchema.getTable(RealmSchema.java:186)
01-12 14:26:36.828 30017-30017/com.dayton.drone W/System.err:     at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:209)
01-12 14:26:36.830 30017-30017/com.dayton.drone W/System.err:     at io.realm.RealmQuery.<init>(RealmQuery.java:141)
01-12 14:26:36.831 30017-30017/com.dayton.drone W/System.err:     at io.realm.RealmQuery.createQuery(RealmQuery.java:80)
01-12 14:26:36.833 30017-30017/com.dayton.drone W/System.err:     at io.realm.Realm.where(Realm.java:1332)
01-12 14:26:36.835 30017-30017/com.dayton.drone W/System.err:     at net.medcorp.models.helper.UserDatabaseHelper.getLoginUser(UserDatabaseHelper.java:62)
01-12 14:26:36.837 30017-30017/com.dayton.drone W/System.err:     at com.dayton.drone.application.ApplicationModel.onCreate(ApplicationModel.java:69)
01-12 14:26:36.839 30017-30017/com.dayton.drone W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
01-12 14:26:36.841 30017-30017/com.dayton.drone W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5505)
01-12 14:26:36.843 30017-30017/com.dayton.drone W/System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
01-12 14:26:36.845 30017-30017/com.dayton.drone W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
01-12 14:26:36.847 30017-30017/com.dayton.drone W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 14:26:36.849 30017-30017/com.dayton.drone W/System.err:     at android.os.Looper.loop(Looper.java:163)
01-12 14:26:36.850 30017-30017/com.dayton.drone W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6337)
01-12 14:26:36.851 30017-30017/com.dayton.drone W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-12 14:26:36.852 30017-30017/com.dayton.drone W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
01-12 14:26:36.853 30017-30017/com.dayton.drone W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

This is my model

public class User extends RealmObject {

    @PrimaryKey
    private int id = (int) Math.floor(Math.random() * Integer.MAX_VALUE);
    private long birthday;
    private int age = 18;
    private int weight = 77;  //kg
    private int height = 175; //cm
    private long createdDate;
    private int sex = 1;      //gender,man:1,female:0
    private String firstName;
    private String lastName;
    private String remarks;
    private String uid;
    private String jwtToken;
    private String jwtId;
    private String userEmail;
    private boolean isLogin;
    private String wechat;
    private String facebook;

    public User() {}

    public User(long createdDate) {
        this.createdDate = createdDate;
    }

    public User(String firstName, String lastName, int sex,String jwtId, long birthday,String facebook ,int age, int weight, int height, long createdDate, String remarks, String wechat) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.sex = sex;
        this.birthday = birthday;
        this.age = age;
        this.facebook = facebook;
        this.weight = weight;
        this.height = height;
        this.jwtId = jwtId;
        this.createdDate = createdDate;
        this.remarks = remarks;
        this.wechat = wechat;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public void setWeight(int weight) {
        this.weight = weight;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public int getAge() {
        return age;
    }

    public int getWeight() {
        return weight;
    }

    public int getHeight() {
        return height;
    }
    public String getFacebook() {
        return facebook;
    }

    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }

    public long getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(long createdDate) {
        this.createdDate = createdDate;
    }

    public String getRemarks() {
        return remarks;
    }

    public int getSex() {
        return sex;
    }

    public void setSex(int sex) {
        this.sex = sex;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public long getBirthday() {
        return birthday;
    }

    public void setBirthday(long birthday) {
        this.birthday = birthday;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getJwtToken() {
        return jwtToken;
    }

    public void setJwtToken(String jwtToken) {
        this.jwtToken = jwtToken;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public boolean isLogin() {
        return isLogin;
    }

    public void setIsLogin(boolean isLogin) {
        this.isLogin = isLogin;
    }

    @Override
    public String toString() {
        return firstName + " " + lastName;
    }

    public String getWechat() {
        return wechat;
    }

    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    public String getJwtId() {
        return jwtId;
    }

    public void setJwtId(String jwtId) {
        this.jwtId = jwtId;
    }

    public int getConsumedCalories(Steps steps) {
        return (int) (2.0 * weight * 3.5 / 200 * (steps.getRunDuration() + steps.getWalkDuration()));
    }

    public double getDistanceTraveled(Steps steps) {
        double distance = ((height * 0.45 / 100) * (steps.getSteps()) / 1000);
        return distance;
    }

}

**Comment by bigfish24** [comment]
This is an issue that would be better suited in [realm-java](https://github.com/realm/realm-java)... though I would ask if you could more clearly state the problem and what you were expecting

**Comment by abhilashawildnet** [comment]
//build gradle (app)
apply plugin: 'com.android.application'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android'
apply plugin: 'realm-android'
apply plugin: 'kotlin-android-extensions'

realm {
    kotlinExtensionsEnabled = true
}
//build gradle (project)
classpath "io.realm:realm-gradle-plugin:5.9.0"

@RealmClass
open class ProfileDataBean :RealmObject() {
    @Required
    @PrimaryKey
    @SerializedName("email")
    @Expose
    open  var email: String = ""
    @SerializedName("id")
    @Expose
    open  var id: Int? = null
}
