### ISSUE TITLE
Incorrect notice when installing Realm Object Server

### ISSUE THREAD

**Issue by revolter** [realm/realm-object-server#332]
## Expected Results

`nvm`'s README says that:

> The script clones the nvm repository to \~/.nvm and adds the source line to your profile (~/.bash_profile, ~/.zshrc, ~/.profile, or ~/.bashrc).

## Actual Results

The following message was printed:

```
!!!! NOTICE !!!!

We have installed NVM, The NodeJS Version Manager for you. In order to continue, you will
need to inject NVM into your current shell.  You do do so by running:

    export NVM_DIR="/Users/revolt/.nvm"
    . "/Users/revolt/.nvm/nvm.sh"  # This loads nvm
```

But:

1. Those lines are instead automatically added.
2. Those lines are actually:

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by revolter** [comment]
Also:

```
◢ Installing dependencies... A little patience is good.undefined
```

**Comment by astigsen** [comment]
Closing this for now as it relates to an outdated version of ROS. Please reopen if the problem resurfaces.
