### ISSUE TITLE
Realm throwing LIMITS_EXCEEDED frequently after updating it 4.2.0 to 4.3.0|4.3.1

### ISSUE THREAD

**Issue by anujjpandey** [realm/realm-object-server#343]
Questions: Why this exception took place after updating realm from 4.2.0 to 4.3.+ , it was working absolutely fine before that even no syncing issue was there but now it is so frequent.

Bugs: Realm is throwing the LIMITS_EXCEEDED  exception 

ObjectServerError Error Message null, LIMITS_EXCEEDED(104)
Connection reset by peer
	at io.realm.SyncSession.notifySessionError(SyncSession.java:178)
	at io.realm.SyncManager.notifyErrorHandler(SyncManager.java:324)
	at dalvik.system.NativeStart.run(Native Method)

## Goals

We need sync of data whether there is connection or not. 

## Expected Results

Syncing should work whether there is active internet connection or not 

## Actual Results

Device was committing location based data so frequently, there was a connection lost for more than 1 hour, so there can be 700-800 commits without internet, and when internet was reconnected the exception took place

FYI: On release version 4.3.0 and 4.3.1 there was an issue that whenever internet was disconnected it was throwing badintent error and sync was stopped after that, but it was not found on 4.3.2 or above realm version but the LIMITS_EXCEEDED is consistent after 4.3.0.

ObjectServerError Error Message null, LIMITS_EXCEEDED(104)
Connection reset by peer
	at io.realm.SyncSession.notifySessionError(SyncSession.java:178)
	at io.realm.SyncManager.notifyErrorHandler(SyncManager.java:324)
	at dalvik.system.NativeStart.run(Native Method)

## Steps to Reproduce

Make 700-800 commit around 272 bites of data, without internet connection.

## Code Sample

1. Create a sync user
2. Create realm object of around 272 bites of data
3. Start committing the data after each 5 second.
4. Disconnect the internet for more than 1 hour.
5. Turn on the internet connection now.

## Version of Realm and Tooling

- Realm Object Server Version: 2.4.4
- Flavor:
  - [ ] Professional
- Server OS & Version: Ubuntu 16.0.4
- Client SDK Version From where issue was found: 4.3.0
- Current Client SDK Version: 4.3.3
- Client OS & Version: 19

**Comment by anujjpandey11** [comment]
Any update.!
