### ISSUE TITLE
Remember last opened local Realm in Realm Studio

### ISSUE THREAD

**Issue by place2book** [realm/realm-object-server#344]
## Goals
When opening Realm Studio, it would be great if it remembered the last x local Realms, that had been opened. The same way as all sorts of editors remember "Last opened" files and so on.

## Expected Results
A list of the last x opened local Realms and those should be clickable, so I can open the same Realm again with 1 click, instead of using the "Open Realm file" and finder.

**Comment by bmunkholm** [comment]
Absolutely agree - it's on the todo list! Thanks for the feedback!

**Comment by bmunkholm** [comment]
Issue moved to [realm/realm-studio #930](https://github.com/realm/realm-studio/issues/930) via [**ZenHub**](https://www.zenhub.com/)
