### ISSUE TITLE
AMI missing for ROS 2

### ISSUE THREAD

**Issue by yuvalkro** [realm/realm-object-server#347]
Hi,

I want to deploy ROS 2 on amazon EC2.
Your link below is missing the AMI's....

https://realm.io/docs/get-started/installation/deployment/

Where can I find them ?

Thank you

Yuval

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by bmunkholm** [comment]
ROS 2 is no longer supported.
