### ISSUE TITLE
Work with data on ROS server side

### ISSUE THREAD

**Issue by artjkee73** [realm/realm-object-server#348]
Hello. I need to implement a social network in the mobile application, in the application I will work with the local database, and then synchronize the data with the Realm Object Server. To handle some user activity, I will use a neural network written in python. How can I implement the work with the data on the server side, which are stored on the Realm Object Server for the needs of the neural network? Is this possible when using the free version (Developer Edition) of the Realm Platform?

**Comment by Zhuinden** [comment]
>  Is this possible when using the free version (Developer Edition) of the Realm Platform?

Well, if you use a client SDK to do the actual writes into the ROS...

**Comment by astigsen** [comment]
Closing as the question was answered. Please reopen if more is needed,
