### ISSUE TITLE
Data Reset when login with different device

### ISSUE THREAD

**Issue by shiangyichen** [realm/realm-object-server#350]
## Goals

Data DO NOT Reset when login with different device

## Expected Results

Data retain when login with different device

## Actual Results

Data is gone when login in different device

## Steps to Reproduce

I run the example project "realm-draw" & "realm-puzzle", it run perfectly with realm object server but when i remove app and retry login with same account, the front project will retain datas i saved, but not the latter. I am confused that it seems like there is no special setting to retain or reset data, 
If i want to retain datas when i removed app and retry login, how do i set?

Haaaaaaalp!
## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by astigsen** [comment]
Closing this as it relates to an outdated version of ROS. Please reopen if the problem resurfaces.
