### ISSUE TITLE
Quick export of whole Classes or filtered Classes to CSV (Realm Studio)

### ISSUE THREAD

**Issue by ajonno** [realm/realm-object-server#351]
## Goals
Quick export of whole Classes or filtered Classes to CSV

## Expected Results
1. User opens a Class and applies a Filter. eg like the screenshot
![2018-03-13_10-54-04](https://user-images.githubusercontent.com/3005269/37315510-38460e1e-26ae-11e8-99b3-ddb29697ad3e.png)

2. The result set can be exported to CSV via right click and/or from menu

**Comment by bmunkholm** [comment]
Issue moved to [realm/realm-studio #926](https://github.com/realm/realm-studio/issues/926) via [**ZenHub**](https://www.zenhub.com/)
