### ISSUE TITLE
[Documentation] "Edit on GitHub" button doesn't work in Realm Platform Docs

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-object-server#353]
That button probably looks like that should not be displayed.

<img width="1220" alt="screen shot 2018-03-23 at 1 57 13" src="https://user-images.githubusercontent.com/40610/37785519-b6b45fee-2e3d-11e8-96be-e76a5de03c17.png">

**Comment by bigfish24** [comment]
@kishikawakatsumi thanks for pointing this out, didn't realize it shows for everyone. I removed it now.
