### ISSUE TITLE
Realm Studio crashes upon connection to Android

### ISSUE THREAD

**Issue by lucaszanella** [realm/realm-object-server#355]
I'm trying to connect to my Android running RealmJs/ReactNative using RealmStudio. I set the connection to localhost:8083. When I click to connect, the app crashes and I see this error on the console:

XHR failed loading: POST "http://localhost:8083/get_property".

Realm version: 2.2.18
Reac-Native version: 0.54.2

can't try with latest realm (2.3.3) because it crashes with react-native: https://github.com/realm/realm-js/issues/1716 https://github.com/realm/realm-js/issues/1711

**Comment by astigsen** [comment]
Closing this for now as it refers to an old version of Studio. Please reopen if it resurfaces with the latest version.
