### ISSUE TITLE
iOS / ROS 3.3 SyncUser.logIn issue 

### ISSUE THREAD

**Issue by ajonno** [realm/realm-object-server#356]
## Goals

login to ROS via iOS using RealmSwift 3.3

## Expected Results

successful login

## Actual Results

error thrown from the SyncUser.logIn method
(note this is currently via HTTP)

![image](https://user-images.githubusercontent.com/3005269/38462828-42fc512e-3b30-11e8-82ad-64c90635174f.png)

__Note: Realm Studio connects just fine to EC2 http://xx.yyy.ttt.cc:9080__
(Contact me via email to get IP address)
```
2018-04-08 12:08:19.685597+1000 ToDo[5016:3495608] [] nw_socket_connect connectx failed (fd 8, 192.168.0.7:8888 stream, pid: 5016, sanitized url: http://xx.yyy.ttt.cc:9080/auth): [64] Host is down
```

## Steps to Reproduce

I just installed and built (pods etc.) the Realm test project from here: 
```https://github.com/realm/my-first-realm-app/tree/master/ios```

in ```Constants.swift``` made following changes:
```
static let MY_INSTANCE_ADDRESS = "xx.yyy.ttt.cc:9080" // <- update this
static let AUTH_URL  = URL(string: "http://\(MY_INSTANCE_ADDRESS)")!
```

Podfile is this:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ToDo' do
  use_frameworks!
  pod 'RealmSwift', '~> 3.3.0'
end
```

I also added the following to ```info.plist``` since we we're hitting an HTTP endpoint:
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

## Code Sample

see above. really very little change made to the Realm example project for iOS other than as noted above.

For the server side:
- running PM2. ```pm2 status``` shows this:
![image](https://user-images.githubusercontent.com/3005269/38462937-e07d477c-3b31-11e8-95cd-63c4f2706afb.png)
- Realm Studio is working fine, can connect to ROS and display realms etc..

## Version of Realm and Tooling

- Realm Object Server Version: __3.0__
![image](https://user-images.githubusercontent.com/3005269/38463010-44b9b4d6-3b33-11e8-90e5-db094e7c0de8.png)

- Flavor:
  - [ ] Developer
  - [X ] Professional
  - [ ] Enterprise
- Server OS & Version: ? AWS, Ubuntu 16.04.4
- Client SDK Version: ? __3.3__
- Client OS & Version: ?  __iOS 11__

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
realm-object-server.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    -- No entries --
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
cat: /var/log/realm-object-server.log: No such file or directory
  </code>
</details>

**Comment by ajonno** [comment]
oky doke so it seems that after restarting ROS - this issue for iOS (only) went away and i could connect to ROS & update the db, get sync, etc 

however i really want to understand why, partic given that Droid was working fine both before and after the ROS re-start? hopefully ROS server logs can help with that, let me know what you recommend and ill do some digging.

**Comment by mgeerling** [comment]
@ajonno , in the email you sent, you said that you were not able to connect to ROS cloud or your self-hosted ROS.  It sounds like you've restarted your self-hosted ROS and are not able to connect.  Are you able to connect to your cloud instance via iOS now as well?

**Comment by ajonno** [comment]
hey Matt, good point sorry i forgot about that Realm Cloud piece. I'll try that today and get back to you.

**Comment by ajonno** [comment]
Matt I tested it out and is working fine now on Realm Cloud too. Pretty certain now I mis-configured something, so will close this ticket. Apologies and thanks for the prompt follow up.
