### ISSUE TITLE
Integrate ADB into Realm Studio

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-server#358]
@eygraber commented on [Wed Apr 11 2018](https://github.com/realm/realm-java/issues/5894)

Using Realm Studio is extremely annoying, because anytime something changes, I have to copy the realm file from the Android device to my local filesystem so that Realm Studio can read it.

There should be an option to give RealmStudio a path on the Android device, and use adb to sync it to the local filesystem.

Not sure where to file requests for Realm Studio, so I put it here.

**Comment by bmunkholm** [comment]
Issue moved to [realm/realm-studio #927](https://github.com/realm/realm-studio/issues/927) via [**ZenHub**](https://www.zenhub.com/)
