### ISSUE TITLE
Sync Only Local

### ISSUE THREAD

**Issue by luigidegiacomo** [realm/realm-object-server#363]
## Goals

I want sync Local & Remote Realm with Realm Cloud

## Expected Results
On Realm Cloud (inspected with Realm Studio) only Realm is created, but nothing classes in.

## Actual Results

MyApp run great on iPhone but don't sync with Realm Cloud

Please help me

**Comment by astigsen** [comment]
Closing this for now as no code to reproduce the problem was supplied. Please reopen with more info if the problem persists.
