### ISSUE TITLE
Realm Object Server issue when using GraphQL

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-object-server#371]
Ive been using GraphQL when getting Data from ROS, and this is what ive observed.

If i do GraphQL calls for 1-2 hours, it will show logs in ROS like this:

0|npm      | info: Realm Object Server version 2.8.1 is starting
0|npm      | info: [sync] Realm sync server started ([realm-core-5.1.2], [realm-sync-2.2.15])
0|npm      | info: [sync] Directory holding persistent state: /home/ec2-user/realm-object-server/data/sync/user_data
0|npm      | info: [sync] Backup mode: master_with_no_slave
0|npm      | info: [sync] Log level: info
0|npm      | info: [sync] Download log compaction is enabled
0|npm      | info: [sync] Max download size: 32000000 bytes
0|npm      | info: [sync] Listening on 127.0.0.1:46731 (sync protocol version 22)
0|npm      | info: [sync] HTTP Connection[1]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[3]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[4]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[7]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[9]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[10]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[13]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[15]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[17]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[19]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[22]: Connection is closed after HTTP response.
0|npm      | info: Realm Object Server has started and is listening on http://0.0.0.0:9080
0|npm      | info: [sync] HTTP Connection[33]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[35]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[43]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[45]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[53]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[55]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[58]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[60]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[63]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[65]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[69]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[71]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[79]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[81]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[113]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[115]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[126]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[128]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[130]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[132]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[135]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[137]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[141]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[143]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[147]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[149]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[151]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[153]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[157]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[159]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[161]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[163]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[165]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[167]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[174]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[176]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[189]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[191]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[210]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[212]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[335]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[337]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[346]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[348]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[351]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[353]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[357]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[359]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[361]: Connection is closed after HTTP response.
0|npm      | info: [sync] HTTP Connection[363]: Connection is closed after HTTP response.
0|npm      | Error: Cannot access realm that has been closed.
0|npm      |     at queryResolver.(anonymous function) (/home/ec2-user/realm-object-server/node_modules/realm-graphql-service/dist/service.js:244:40)
0|npm      |     at resolveFieldValueOrError (/home/ec2-user/xeleqt-object-server/node_modules/graphql/execution/execute.js:498:12)
0|npm      |     at resolveField (/home/ec2-user/realm-object-server/node_modules/graphql/execution/execute.js:462:16)
0|npm      |     at /home/ec2-user/realm-object-server/node_modules/graphql/execution/execute.js:311:18
0|npm      |     at Array.reduce (<anonymous>)
0|npm      |     at executeFields (/home/ec2-user/realm-object-server/node_modules/graphql/execution/execute.js:308:42)
0|npm      |     at executeOperation (/home/ec2-user/realm-object-server/node_modules/graphql/execution/execute.js:236:122)
0|npm      |     at executeImpl (/home/ec2-user/realm-object-server/node_modules/graphql/execution/execute.js:133:26)
0|npm      |     at Object.execute (/home/ec2-user/realm-object-server/node_modules/graphql/execution/execute.js:110:229)
0|npm      |     at doRunQuery (/home/ec2-user/realm-object-server/node_modules/apollo-server-core/dist/runQuery.js:122:42)

Due to this, i ended up restarting the ROS again and again. It happens frequently for about 5 times i day.

I hope someone can help me with this. Thanks in advance.

**Comment by astigsen** [comment]
Closing this for now as it relates to an outdated version of ROS. Please reopen if the issue resurfaces.
