### ISSUE TITLE
Opening a realm file with Realm Studio on Mac makes the file unreadable by Simulator

### ISSUE THREAD

**Issue by kakubei** [realm/realm-object-server#372]
## Goals

Open realm file in Realm Studio, close Realm Studio, be able to use the realm file on the iOS simulator.
## Expected Results

File should be readable from the simulator after closing Realm Studio.

## Actual Results

Realm throws error: underlying	std::__1::string "Unsupported Realm file format version"	

#1	0x000000010908f48e in translate_file_exception(realm::StringData, bool) at /work/farepilot/Pods/Realm/Realm/ObjectStore/src/shared_realm.cpp:115
#2	0x000000010908d318 in realm::Realm::open_with_config(realm::Realm::Config const&, std::__1::unique_ptr<realm::Replication, std::__1::default_delete<realm::Replication> >&, std::__1::unique_ptr<realm::SharedGroup, std::__1::default_delete<realm::SharedGroup> >&, std::__1::unique_ptr<realm::Group, std::__1::default_delete<realm::Group> >&, realm::Realm*) at /work/farepilot/Pods/Realm/Realm/ObjectStore/src/shared_realm.cpp:185
#3	0x000000010908aff7 in realm::Realm::Realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) at /work/farepilot/Pods/Realm/Realm/ObjectStore/src/shared_realm.cpp:51
#4	0x0000000108e354e3 in realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler::make_shared_enabler(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) at /work/farepilot/Pods/Realm/include/shared_realm.hpp:304
#5	0x0000000108e353d5 in realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler::make_shared_enabler(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) at /work/farepilot/Pods/Realm/include/shared_realm.hpp:304
#6	0x0000000108e349dc in std::__1::__compressed_pair_elem<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler, 1, false>::__compressed_pair_elem<realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&, 0ul, 1ul>(std::__1::piecewise_construct_t, std::__1::tuple<realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&>, std::__1::__tuple_indices<0ul, 1ul>) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2057
#7	0x0000000108e348d5 in std::__1::__compressed_pair<std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>, realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>::__compressed_pair<std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>&, realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>&>, std::__1::tuple<realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&>) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2159
#8	0x0000000108e34820 in std::__1::__compressed_pair<std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>, realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>::__compressed_pair<std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>&, realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&>(std::__1::piecewise_construct_t, std::__1::tuple<std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>&>, std::__1::tuple<realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&>) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2160
#9	0x0000000108e347da in std::__1::__shared_ptr_emplace<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler, std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler> >::__shared_ptr_emplace<realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator> >(std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>, realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3572
#10	0x0000000108e3449d in std::__1::__shared_ptr_emplace<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler, std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler> >::__shared_ptr_emplace<realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator> >(std::__1::allocator<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>, realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3573
#11	0x0000000108e3445a in std::__1::shared_ptr<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler> std::__1::shared_ptr<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>::make_shared<realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator> >(realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4230
#12	0x0000000108e220c5 in std::__1::enable_if<!(is_array<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>::value), std::__1::shared_ptr<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler> >::type std::__1::make_shared<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler, realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator> >(realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4600
#13	0x0000000108e2209a in realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) at /work/farepilot/Pods/Realm/include/shared_realm.hpp:306
#14	0x0000000108e20ed1 in realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config) at /work/farepilot/Pods/Realm/Realm/ObjectStore/src/impl/realm_coordinator.cpp:232
#15	0x00000001090907b6 in realm::Realm::get_shared_realm(realm::Realm::Config) at /work/farepilot/Pods/Realm/Realm/ObjectStore/src/shared_realm.cpp:221
#16	0x000000010900f86c in ::+[RLMRealm realmWithConfiguration:error:](RLMRealmConfiguration *, NSError **) at /work/farepilot/Pods/Realm/Realm/RLMRealm.mm:370
#17	0x000000010994f47a in @nonobjc RLMRealm.__allocating_init(configuration:) ()
#18	0x000000010994f304 in Realm.init() at /work/farepilot/Pods/RealmSwift/RealmSwift/Realm.swift:67
## Steps to Reproduce

1. Store realm objects from an app using the simulator
2. Open the realm file in Realm Studio
3. Close Realm Studio
4. Run simulator again
5. boom!
## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6): 
- Client SDK Version: ?
 Realm (2.10.2):
    - Realm/Headers (= 2.10.2)
  - Realm/Headers (2.10.2)
  - RealmSwift (2.10.2):
    - Realm (= 2.10.2)
- Client OS & Version: ?
Mac OS High Sierra version 10.13.4 (17E202)

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by astigsen** [comment]
Closing this as it relates to an outdated version of Studio. Please reopen if you still encounter this with the latest version.
