### ISSUE TITLE
"Invalid realm type" error after ROS migration.

### ISSUE THREAD

**Issue by molind** [realm/realm-object-server#374]
I've just upgraded ROS from 2.7.2 to 3.4.3. And now it becomes interesting. Our users can't open their synced realms because of error.

        [RLMSyncManager sharedManager].errorHandler = ^(NSError *error, RLMSyncSession *session) {
            LogError(@"RLMSyncManager error %@", error);
        };

RLMSyncManager returns `Error Domain=io.realm.sync Code=8 "(null)" UserInfo={underlying_error=Error Domain=io.realm.sync.auth Code=3 "(null)" UserInfo={statusCode=400}}`

And that's fine seems something with our auth credentials on server. But server log tells me: `HTTP response: be33008a-ae5e-4fa1-bab2-f11b40f11b55 {"type":"https://realm.io/docs/object-server/problems/invalid-realm-type","title":"The type of the Realm file was invalid.","status":400,"code":619}`

Which is basically `You're trying to open partial file with non partial configuration`. But client and server uses same `full` realms. And no modifications happened.

Seems this error returned as false positive.

I've tried to grand administrator permission to that user. It could open his database. But as soon I remove admin permission it sees same error chain.

New users is not affected by this migration issue.

Is there anything I could do to let my users connect to their data?

## Goals

Open synchronized realm

## Expected Results

It should open

## Actual Results

Server returns `HTTP response: be33008a-ae5e-4fa1-bab2-f11b40f11b55 {"type":"https://realm.io/docs/object-server/problems/invalid-realm-type","title":"The type of the Realm file was invalid.","status":400,"code":619}`

## Steps to Reproduce

I could send you user folder from our server or any part of server log.

## Version of Realm and Tooling

- Realm Object Server Version: 3.4.3
- Server OS & Version: Ubuntu 16.04
- Client SDK Version: 3.1.1, 3.5.0
- Client OS & Version: iOS

## Logs

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
Open files in Realm Object Server: {"regular":277,"directory":0,"character-device":1,"block-device":0,"pipe":18,"symbolic-link":0,"socket":143,"unknown":8,"total":447}
4:38:33 PM
HTTP response: 1d11b856-c059-400a-886b-f27b9cd92578 {"type":"https://realm.io/docs/object-server/problems/invalid-realm-type","title":"The type of the Realm file was invalid.","status":400,"code":619}
  </code>
</details>

**Comment by ianpward** [comment]
@molind Can you open Studio and connect to the ROS and then do View> Show System Realms. Then open the /__admin realm and go to the RealmFile class. Find your Realm and change the type to `full` or `reference` if you are using partial sync.

**Comment by nirinchev** [comment]
This should have been fixed with ROS 3.4.3. Can you double check that this is the version that is running on your server? If you go to `node_modules/realm-object-server/dist/services/AuthService.js`, there should be a function `ensureRealmOfType` with the following body:

```js
static ensureRealmOfType(requiredType, actualType) {
    if (!(actualType in realms_1.RealmType)) {
        actualType = realms_1.RealmType.full;
    }
    if (actualType !== requiredType) {
        throw new errors.realm.InvalidRealmType(requiredType, actualType);
    }
}
```

**Comment by molind** [comment]
@ianpward Checked it. `realmType` was empty for all realms.

@nirinchev Yes, indeed. I used 3.4.2, and now after upgrade to 3.4.3 everything works fine, thanks!

**Comment by Hakob1987** [comment]
Hi everyone ;)

[https://i.stack.imgur.com/T7B8V.png](url)
What reason can it be people?

**Comment by Hakob1987** [comment]
![default](https://user-images.githubusercontent.com/24206808/44206484-fd1de400-a16a-11e8-97b5-cf6cd21de6e2.png)
