### ISSUE TITLE
Auto create a new realm file when login fail

### ISSUE THREAD

**Issue by tranhoangvuit** [realm/realm-object-server#375]
Hi Realm team,
After update from realm 2.3.0 to 3.3.0 on the server. In the realm object server always create a new realm object with an owner is `nobody`. Or if we login fails, it also creates new realm with an owner is `nobody`. How can I fix it? 

![image](https://user-images.githubusercontent.com/21276822/40264678-e31d97b0-5b53-11e8-9fc7-9bb7d0dc9094.png)

The second one, I used realm with client used.Net language. In the client, they used 3.0.0. But after I reset everything, it only works in some time. After that, the error `Bad changeset DOWNLOAD` or `cannot sync new data`.

![image](https://user-images.githubusercontent.com/21276822/40264660-8009a18c-5b53-11e8-8238-af0128654aea.png)

## Version of Realm and Tooling

- Realm Object Server Version: 3.3.0
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ?  Ubuntu
- Client SDK Version:  .NET 3.0.0

**Comment by astigsen** [comment]
Closing this for now as it relates to an outdated version of ROS. Please reopen if the problem resurfaces.
