### ISSUE TITLE
Realm Studio 1.21 - screen goes blank after deleting collections or realms

### ISSUE THREAD

**Issue by SogoGolf** [realm/realm-object-server#376]
- installed on Mac OSX 10.13.4

- deleted a Realm. saw this (see screenshot). tried a few times, same result for any/all Realms.

![2018-05-19_18-39-39](https://user-images.githubusercontent.com/19580787/40266775-5dd352e8-5b94-11e8-805c-56a1a10c1b89.png)

**Comment by guatedude2** [comment]
I too have the same issue

**Comment by ElMoribond** [comment]
Same for me on Windows 10.
It's impossible to use it, I downgrade to 1.20.

**Comment by bmunkholm** [comment]
Issue moved to [realm/realm-studio #864](https://github.com/realm/realm-studio/issues/864) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kraenhansen** [comment]
Please see my comment on the Studio repository: https://github.com/realm/realm-studio/issues/864#issuecomment-401596496
