### ISSUE TITLE
Bad Gateway Error 502-504

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-object-server#377]
## Goals

Connect to realm object server cloud instance.

## Expected Results

Managing synced realms.

## Actual Results

502 Bad Gateway
<img width="767" alt="failed while synchronizing realm bad websocket handshake response 502-504 received 2018-05-24 at 09 39 27" src="https://user-images.githubusercontent.com/7915553/40476654-7a3be818-5f3c-11e8-98fb-e5d289c93920.png">

2018-05-24 10:09:27.968861+0100 Exercise[981:26108] Sync: Connection[1]: Resolving 'ties.us1.cloud.realm.io:443'
2018-05-24 10:09:27.973437+0100 Exercise[981:26108] Sync: Connection[1]: Connecting to endpoint '88.209.130.242:443' (1/3)
2018-05-24 10:09:28.165690+0100 Exercise[981:26108] Sync: Connection[1]: Connected to endpoint '88.209.130.242:443' (from '192.168.0.13:50996')
2018-05-24 10:09:28.943064+0100 Exercise[981:26108] Sync: Connection[1]: WebSocket::initiate_client_handshake()
2018-05-24 10:09:29.137536+0100 Exercise[981:26108] Sync: Connection[1]: WebSocket::handle_http_response_received()
2018-05-24 10:09:29.137747+0100 Exercise[981:26108] Sync: Connection[1]: Websocket: Expected HTTP response 101 Switching Protocols, but received:
HTTP/1.1 502 Bad Gateway
Connection: keep-alive
Content-Length: 173
Content-Type: text/html
Date: Thu, 24 May 2018 09:09:51 GMT
Server: nginx/1.13.5
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.13.5</center>
</body>
</html>

<img width="767" alt="failed while synchronizing realm bad websocket handshake response 502-504 received 2018-05-24 at 09 39 27" src="https://user-images.githubusercontent.com/7915553/40485999-f481a8cc-5f57-11e8-881f-8013ee8da4e7.png">

## Steps to Reproduce

Try to connect to my realm cloud instance

## Code Sample

https://github.com/realm/my-first-realm-app/tree/master/ios/SyncIntro
unmodified

## Version of Realm and Tooling

- Realm Object Server Version: Cloud
- Flavor: Cloud
- Server OS & Version: ? (e.g. CentOS 6) 
- Client SDK Version: 3.5.0
- Client OS & Version: MacOSX 10.13.4 (High Sierra)

## Logs

HTTP response: a3e5efcc-c760-40fb-bc1d-38c9340dfc4f {"type":"https://realm.io/docs/object-server/problems/access-denied","title":"The path is invalid or current user has no access.","status":403,"code":614}
httpYesterday at 2:39 PM
HTTP response: 6cbac98f-d625-4f73-9322-1c3668611d5d {"type":"https://realm.io/docs/object-server/problems/access-denied","title":"The path is invalid or current user has no access.","status":403,"code":614}
httpYesterday at 2:39 PM
HTTP response: cbba3fa5-1fc8-4588-acb0-02fbe88c2dfa {"type":"https://realm.io/docs/object-server/problems/access-denied","title":"The path is invalid or current user has no access.","status":403,"code":614}
httpYesterday at 2:39 PM
Internal sync error (path: /__revocation). Message: Bad user authentication (BIND, REFRESH), category: realm::sync::ProtocolError, code: 203, name: Error.
12:53:55 AM
Internal sync error (path: /__password). Message: Bad user authentication (BIND, REFRESH), category: realm::sync::ProtocolError, code: 203, name: Error.
12:55:25 AM
Internal sync error (path: /__wildcardpermissions). Message: Bad user authentication (BIND, REFRESH), category: realm::sync::ProtocolError, code: 203, name: Error.
12:58:29 AM
Internal sync error (path: /__perm). Message: Bad user authentication (BIND, REFRESH), category: realm::sync::ProtocolError, code: 203, name: Error.
1:07:00 AM
Internal sync error (path: /__configuration). Message: Bad user authentication (BIND, REFRESH), category: realm::sync::ProtocolError, code: 203, name: Error.
1:12:30 AM
Internal sync error (path: /__admin). Message: Bad user authentication (BIND, REFRESH), category: realm::sync::ProtocolError, code: 203, name: Error.
1:13:55 AM
Internal sync error (path: /default). Message: Bad user authentication (BIND, REFRESH), category: realm::sync::ProtocolError, code: 203, name: Error.
<details>

**Comment by DanielAsher** [comment]
This cloud error is compounded by the limitation on a single cloud instance.
<img width="508" alt="screen shot 2018-05-24 at 13 47 29" src="https://user-images.githubusercontent.com/7915553/40486439-2aa89f9a-5f59-11e8-97b3-a9adb2603cae.png">

**Comment by howdyhyber** [comment]
It also appears to me.

**Comment by astigsen** [comment]
Closing for now as it relates to an old ROS version. Please reopen if it resurfaces.
