### ISSUE TITLE
Realm object server asking featureToken

### ISSUE THREAD

**Issue by kunaldodiya** [realm/realm-object-server#383]
I am very new and dont know what is featureToken.  How to get it??  On searching google i found,  i have to purchase professional edition to get it, any way that i can use it free.. ??? I was in impression that it is open source.

**Comment by astigsen** [comment]
Closing this as it refers to an outdated version of ROS. The feature token is no longer needed when using the cloud version of ROS. Please reopen if the problem resurfaces.
