### ISSUE TITLE
cpu & network usage is too high when connected realm-js client on the node-js server

### ISSUE THREAD

**Issue by bigparksh** [realm/realm-object-server#386]
## Goals
I have been using realm-object-server with Android & iOS clients for about 11 months.
Recently, I connected to the ROS using realm-js client on node-js server.
Then, CPU and network usage of ROS is increasing too much.

Normally, if android & iOS client is connected, the CPU usage does not exceed 10%. However, when the realm-js client is connected for testing, the CPU usage increases to 100%.

Below is an old stackoverflow issue.
https://stackoverflow.com/questions/50077066/cpu-network-usage-is-too-high-when-connected-realm-js-client-on-the-node-js-se

And I got a 100% case about this issue.
1. Set the accessTokenTtl to 36 minutes or longer  with server.start on the realm object server. (index.js file)
2. Then realm js client re-connect to the ROS.

## Expected Results
CPU usage should be normal.

## Actual Results
CPU usage is over 100%.

## Code Sample
`accessTokenTtl: (1000 * 60 * 60)`

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [0] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6) ubuntu 16.4
- Client SDK Version: ? node js 2.4
- Client OS & Version: ? node 8.4

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by astigsen** [comment]
@bigparksh is this still an issue for you with the latest version of ROS?

**Comment by astigsen** [comment]
Closing this for now due to lack of response from reporter. Please reopen if the problem resurfaces.
