### ISSUE TITLE
Realm Upgrade

### ISSUE THREAD

**Issue by glennmd** [realm/realm-object-server#388]
When do you expect to support iOS12 with system Mojave? I hesitate upgrading my Swift/Xcode/Realm project to the beta versions of iOS12 and Mojave since Realm has been a laggard when it comes to upgrading to latest versions of Xcode/Swift (without having to install Realm with CocoaPods).  

Glenn Tisman

**Comment by nirinchev** [comment]
There is an issue about it in the Cocoa repository: https://github.com/realm/realm-cocoa/issues/5812.
