### ISSUE TITLE
Realm-Vacuum Documentation Inquiry

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-object-server#390]
Do you have documentation for realm-vacuum? According to the thread #357 , realm-vacuum will help lessen the storage consumption of ROS,  as what i have understood. 

Currently our server has 256GB storage and 14GB RAM. After 5 months or using it, its storage consumption vastly grew to 215GB(84%). We already experienced that the storage is already full, that the realm will just restart on its own.

**Comment by mgeerling** [comment]
@howdyhyber -- I sent you an email on this.  I will be publishing directions to the website in the near term

**Comment by mgeerling** [comment]
Just closing the loop.  The [vacuum utility is documented here](https://docs.realm.io/platform/self-hosted/manage/server-side-file-growth#vacuum-utility)
