### ISSUE TITLE
 Error what():  set: row ndx out of range

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-object-server#392]
We have encountered an error something like this:

terminate called after throwing an instance of 'realm::sync::BadChangesetError'
0|nextgo-r |   what():  set: row ndx out of range
PM2        | App [nextgo-ros] with id [0] and pid [31707], exited with code [0] via signal [SIGABRT]
PM2        | Starting execution sequence in -fork mode- for app name:nextgo-ros id:0
PM2        | App name:nextgo-ros id:0 online

ROS Version : 3.6.12 GraphQL 2.6.0

**Comment by astigsen** [comment]
Closing this for now as it relates to an outdated version of ROS and the BadChangesetError has been fixed in the latest version. Please reopen if the problem resurfaces.
