### ISSUE TITLE
Save named passwords for local files

### ISSUE THREAD

**Issue by KDean-Dolphin** [realm/realm-object-server#395]
## Goals

When using Realm Studio to open a realm file in a container downloaded from a development device, either remember the previous password or use a list of named passwords.

## Expected Results

Realm Studio remembers the previous password or prompts with a list of named passwords.

## Actual Results

Realm Studio prompts for a password every time.

## Steps to Reproduce

1. Create a realm file with an encryption key on a device.
2. Download the device container to your Mac.
3. Double-click the realm file in the container.
4. Enter password.

What I'd really like to see here is the ability to name and store passwords (e.g. "Kevin's iPhone - App 1", "Kevin's iPhone - App 2", "Kevin's iPad - App 1", etc.) so that when I open a realm file from a container I can select which password I want to use to open the file. Passwords are randomly generated per device and app per the recommendations in the documentation, so I've added logging to my apps that prints the passwords to the console when in development mode so I can debug the content.

Given the relative complexity of named passwords, I'll settle for remembering the last password.

## Version of Realm and Tooling

Realm Swift 3.7.6
Realm Studio 2.8.0

**Comment by bmunkholm** [comment]
@KDean-Dolphin Moving this to the Studio repo.

**Comment by bmunkholm** [comment]
Issue moved to [realm/realm-studio #931](https://github.com/realm/realm-studio/issues/931) via [**ZenHub**](https://www.zenhub.com/)
