### ISSUE TITLE
Can't Install Realm Studio Mac

### ISSUE THREAD

**Issue by barrysohl** [realm/realm-object-server#397]
Latest download of Realm Studio will not install on Mac High Sierra (10.13.6). See MacOS error message. It is making it very hard to get started using Realm Platform. Please help!

<img width="424" alt="screen shot 2018-10-02 at 9 06 42 pm" src="https://user-images.githubusercontent.com/9275704/46389713-7ffdee00-c688-11e8-8b51-a45b11639b16.png">

**Comment by nirinchev** [comment]
Which version of Studio is that and where did you download it from? Did it automatically update to that version?

**Comment by barrysohl** [comment]
Thanks for the quick response. This is with the current .dmg download on the Realm website (filename 'Realm Studio-2.9.0.dmg’). No previous install was on this Mac, so no automatic update.

Downloaded here:
https://realm.io/products/realm-studio/#download-studio


-Barry

**Comment by nirinchev** [comment]
Sorry about that - I verified that the mac binary that was uploaded to S3 was corrupted and had some missing libraries. I've uploaded a correct version that should work properly. Can you try to download it again and check if you still get the error?

**Comment by barrysohl** [comment]
It’s working now, thanks!

-Barry
