### ISSUE TITLE
ROS no longer lets you select multiple rows and right click for delete...

### ISSUE THREAD

**Issue by cyphire** [realm/realm-object-server#398]
## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <pre>Paste output here</pre>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <pre>Paste output here</pre>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <pre>Paste output here</pre>
</details>

**Comment by nirinchev** [comment]
Does this issue refer to Realm Studio?

**Comment by cyphire** [comment]
Yes correct.

**Comment by nirinchev** [comment]
Okay, I'll mark this as a duplicate to https://github.com/realm/realm-studio/issues/959 then.
