### ISSUE TITLE
error: [http] HTTP upgrade failed (service did not respond properly)

### ISSUE THREAD

**Issue by grafele** [realm/realm-object-server#401]
## Goals

Sync my app with realm object server.

## Expected Results

Sync works as it did before.

## Actual Results

On the client i get the following log:
```
Sync: Connection[1]: Websocket: Expected HTTP response 101 Switching Protocols, but received:
HTTP/1.1 503 Service Unavailable

Server: Realm-Object-Server/3.12.2
```

On the server side I get this message:

```
error: [http] HTTP upgrade failed (service did not respond properly) {"type":"https://realm.io/docs/object-server/problems/service-unavailable","title":"The requested service is temporarily unavailable.","status":503,"code":802}
Request:  eed1dd54-2a34-421a-a3e6-b2e765947b1a
GET /realm-sync/%2F__admin HTTP/1.1
Authorization: Realm-Access-Token version=1 token="eyJhcHBfaWQiOiJpby5yZWFsbS5hdXRoIiwiaWRlbnRpdHkiOiJfX2FkbWluIiwiYWNjZXNzIjpbImRvd25sb2FkIiwidXBsb2FkIiwibWFuYWdlIl0sInNhbHQiOiIzZTNhOTRkNiIsImNhblNraXBSZXZvY2F0aW9uQ2hlY2siOnRydWV9:PNreybb81LnbZL8lBThLOxpC88K34kv6QIAzAzSxeulYFxBunkpD1VoCT4XD
iR/PnBbmheZof3I+khEqZOcUQfFrunTZED8BajH/gwMVj8ru9nPO3sCKSEHpEAcKTkKO2tbEVPikPo+gi9VqE1JNGZxTp6IfZgP9p9f3vZ3cr7GsWZTlh3ayHHH60qQw8EGDzkydKLo7Sn4jh4udQ53SFMFFDrhhksUqE5W/h+wiDo9weUuj/p3Rou+0xcN1HCKLh8beidWqVvPBvYTtgItXAuAbUOSRmhb5gzZ2IE2C2gPmZ2CoFcmHvWExzXivRuSOosTMJaSm3KXbp6gyL8Gi7Q=="
Connection: Upgrade
Host: 0.0.0.0
Sec-WebSocket-Key: v0M+uwCTW9YHbG/lETUfIQ==
Sec-WebSocket-Protocol: io.realm.sync.25
Sec-WebSocket-Version: 13
Upgrade: websocket

Response:
HTTP/1.1 503 Service Unavailable
Server: Realm-Object-Server/3.12.2


Detected an unhandled promise rejection at:  Promise { <rejected> 'Bad WebSocket response 503 service unavailable' } , reason:  Bad WebSocket response 503 service unavailable
Detected an unhandled promise rejection at:  Promise { <rejected> 'Bad WebSocket response 503 service unavailable' } , reason:  Bad WebSocket response 503 service unavailable
```

## Steps to Reproduce

Sync your app with realm object server version 3.12.2 (same happened at 3.11.5).

## Code Sample

Nothing special here. Normal Realm.open on client side.

## Version of Realm and Tooling

- Realm Object Server Version: 3.12.2
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [X] Enterprise
- Server OS & Version: CentOS 6
- Client SDK Version: 3.11.0
- Client OS & Version: 12.0.1

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <pre>Unit realm-object-server.service could not be found</pre>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <pre>-- No entries --</pre>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <pre>Paste output here</pre>
</details>

**Comment by mgeerling** [comment]
@grafele -- can you [open a support ticket here](https://support.realm.io/helpdesk)?  With this, can you please include the full logs (ideally at the debug level) as well as any information about what has changed in your setup, app, etc since this starting occurring?

**Comment by bmunkholm** [comment]
Closing as this is handled through support.
