### ISSUE TITLE
"Build a demo project" 404 Link rot

### ISSUE THREAD

**Issue by hellmanhellman** [realm/realm-object-server#404]
## Goals
Trying to follow the links "Start with iOS" and "Start with Android" after starting the Realm Cloud free trial.

## Expected Results
Access to tutorials.

## Actual Results
404 error on both links.

## Steps to Reproduce
After creating an instance in the cloud.realm.io dashboard, click the instance name to see the "Getting Started" page (titled "Your instance is ready". The links further down to the tutorials fail, because they point (respectively) to the invalid URLs 

https://docs.realm.io/v/3.x/getting-started-1/ios-quick-start
https://docs.realm.io/platform/v/3.x/getting-started/android-quick-start

instead of the valid URL
https://docs.realm.io/platform/getting-started-1

**Comment by bmunkholm** [comment]
Thanks for reporting this @hellmanhellman. We are aware of this and have fixed it. It's just awaiting deployment. Thanks!

**Comment by hellmanhellman** [comment]
OK great! Amazing response time.
