### ISSUE TITLE
Wrong command on https://docs.realm.io/server/installation/kubernetes-deployment-instructions

### ISSUE THREAD

**Issue by programaths** [realm/realm-object-server#408]
## Goals

Follow the "kubernetes-deployment-instructions"

## Expected Results

It works as described

## Actual Results

Wrong command

## Steps to Reproduce

Follow guide up to https://docs.realm.io/server/installation/kubernetes-deployment-instructions#overriding-defaults

This command will fail: `helm upgrade foolish-octopus realm-object-server -f overrides.yaml`
Because one need to do this instead: `helm upgrade braided-armadillo realm/realm-object-server -f overrides.yaml`

(Replacing *realm-object-server* with *realm/realm-object-server*

## Code Sample

See above
## Version of Realm and Tooling
- Page URL: https://docs.realm.io/server/installation/kubernetes-deployment-instructions#overriding-defaults
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [X] Enterprise
- Server OS & Version: ? (uname -a) Linux christian-Aspire-TC-605 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
<details>
  <summary>kubectl version</summary>
  <pre>Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}</pre>
</details>

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <pre>Paste output here</pre>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <pre>Paste output here</pre>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <pre>Paste output here</pre>
</details>

**Comment by mgeerling** [comment]
Fixed and deployed
