### ISSUE TITLE
Improvement on Guide with minikube

### ISSUE THREAD

**Issue by programaths** [realm/realm-object-server#409]
The [guide](https://docs.realm.io/server/installation/kubernetes-deployment-instructions#overriding-defaults) explains that we can open http://localhost:30080. This does not work with **minikube** on **kubuntu**.

With minikube, the correct endpoints becomes:
`open $(minikube ip):30080`

Also, on Kubuntu, it's more specifically:

`xdg-open $(minikube ip):30080`

**Comment by mgeerling** [comment]
added clarifications
