### ISSUE TITLE
Unable to launch ROS

### ISSUE THREAD

**Issue by joelbourbon** [realm/realm-object-server#413]
## Goals

Install ROS on a brand new VM on Azure.

## Expected Results

Able to start the server after a fresh install following [this guide.](https://docs.realm.io/server/installation/manual-install#manual-install)

## Actual Results
``` bash
> my-ros-app@1.0.0 start /home/(redacted)/realm/realm-mobile-server
> npm run build && node dist/index.js

> my-ros-app@1.0.0 build /home/(redacted)/realm/realm-mobile-server
> rm -rf dist; ./node_modules/.bin/tsc

node_modules/@types/node/index.d.ts(75,15): error TS2300: Duplicate identifier 'SharedArrayBuffer'.
node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts(24,11): error TS2300: Duplicate identifier 'SharedArrayBuffer'.
node_modules/typescript/lib/lib.es2017.sharedmemory.d
```

## Steps to Reproduce

https://docs.realm.io/server/installation/manual-install#manual-install

## Version of Realm and Tooling

- Realm Object Server Version: 3.18.3
- Flavor: Self-hosted
- Server OS & Version: Ubuntu 18.04.2 LTS
- Client SDK Version: N/A
- Client OS & Version: N/A

NB: I did the exact same thing last week and it worked. Something apparently changed in the last version of ROS.

**Comment by roberhofer** [comment]
@fealebenpae : can you confirm whether this is addressed in the 3.18.4 release? 
Seem that Ian had issues installing on his laptop as well.

**Comment by joelbourbon** [comment]
Hi @roberhofer,

Thanks for the prompt reply.

I just tested updating ROS to the latest (3.18.4), wiped my project et re-initialized it: same results.
Also tested on a brand new VM with the latest version: same results.

I deployed your solution last week on another VM and everything was great.
Don't hesitate to contact me if you want me to test something.

Thanks,

**Comment by fealebenpae** [comment]
Hey @joelbourbon - you can fix this by opening `tsconfig.json` and deleting `esnext` from the `lib` array. We'll be sure to fix this in a new release.

**Comment by joelbourbon** [comment]
Thank @fealebenpae! It worked!

I hope you find a way to fix that in your next release 😄

**Comment by JakinMiao** [comment]
> esnext



> Hey @joelbourbon - you can fix this by opening `tsconfig.json` and deleting `esnext` from the `lib` array. We'll be sure to fix this in a new release.
tsconfig.json where ? my project's tsconfig.json has no 


> Hey @joelbourbon - you can fix this by opening `tsconfig.json` and deleting `esnext` from the `lib` array. We'll be sure to fix this in a new release.

i can't find `esnext` from the `lib` array . please help me

**Comment by ayushprashar** [comment]
@fealebenpae I tried doing the same and it resulted in an error message that the feature token is invalid.

**Comment by joelbourbon** [comment]
@ayushprashar you forgot to do one step: https://docs.realm.io/server/installation/manual-install#1-add-your-feature-token
