### ISSUE TITLE
Anonymous to JWT user

### ISSUE THREAD

**Issue by Perjan** [realm/realm-object-server#419]
We have this use case, where you start the app as an anonymous user and later you can log in.
What is the best way to access all the data that you had as an anonymous user?
Wa cannot find any solution...

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Cloud
  - [ ] Self-hosted
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <pre>Paste output here</pre>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <pre>Paste output here</pre>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <pre>Paste output here</pre>
</details>

**Comment by bmunkholm** [comment]
Hi @Perjan - sorry for the late response. This repo is however only intended for bug reports. However, it's understandable that you haven't found anything documented as we don't currently have a good way to handle this automatically. It's a use-case we would like to support more automatically, but until we do, your best bet is to handle this manually. Either sharing the Realm or copying it over manually to the new user.
