### ISSUE TITLE
Realm Data is not fetched when i plug out and again plug my battery directly and internet connection is off, but when i on internet connection it start syncing my data. Does Realm library needs internet connection to retrieve the data ?

### ISSUE THREAD

**Issue by vipulsingh0** [realm/realm-object-server#424]

**Comment by bmunkholm** [comment]
Realm does not need an internet connection to show the data that has once been downloaded and synced to the device. That's the whole point of syncing and having state available offline. If you are experiencing that then you are doing something wrong :-).
