### ISSUE TITLE
Auth with a custom provider

### ISSUE THREAD

**Issue by pierre-moire** [realm/realm-object-server#425]
## Goals

I would like to connect with a custom auth provider on a ros entreprise setup but I get an error during login. The client is a JS GraphQL client

## Expected Results

I expect to get a response with profile infos

## Actual Results

The server returns an error

## Steps to Reproduce

Server side the provider is declared (based on https://github.com/realm/realm-sync-samples/blob/master/22-custom-auth/src/index.ts): 
 
```
const authService = new ros.AuthService();
authService.addProvider(new ros.auth.PasswordAuthProvider({autoCreateAdminUser: true}));
authService.addProvider(new CrmProvider());

const startConfig = {
    services: [
        new ros.SyncProxyService(),
        authService,
        new ros.RealmDirectoryService(),
        new ros.PermissionsService(),
        new ros.LogService(),
        new ros.HealthService(),
```

Client side, I tried with the following call:

const credentials = await Credentials.Custom("crm", "", { username, password });

and also directly with 

```
{
	app_id: "",
	provider: "crm",
	data: username,
	user_info: {
		username: username,
		password: password
	}
}
```

Problem is, the server indicates the following result: 
```
{type: "https://docs.realm.io/server/troubleshoot/errors#invalid-parameters",…}
code: 601
invalid_params: [{name: "provider", reason: "Invalid parameter 'provider'!"}]
status: 400
title: "Your request parameters did not validate."
type: "https://docs.realm.io/server/troubleshoot/errors#invalid-parameters"
```

## Version of Realm and Tooling

- Realm Object Server Version: 3.19.0
- Flavor:
  - [ ] Cloud
  - [X] Self-hosted
- Server OS & Version: ? Ubuntu Xenial

## Logs

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <pre>
Open files in Realm Object Server: {"regular":35,"directory":0,"character-device":1,"block-device":0,"pipe":20,"symbolic-link":0,"socket":23,"unknown":8,"total":87}
10.100.166.62 - OPTIONS /auth HTTP/1.1 204 0 - 0.185 ms
HTTP response: 7bab1502-6227-4a9d-8766-5c94f0cb32cf {"type":"https://docs.realm.io/server/troubleshoot/errors#invalid-parameters","title":"Your request parameters did not validate.","status":400,"code":601,"invalid_params":[{"name":"provider","reason":"Invalid parameter 'provider'!"}]}
Returning error response
context: Object
status: 400
title: "Your request parameters did not validate."
path: "invalid-parameters"
code: 601
invalidParams: Array[1]
0: Object
name: "provider"
reason: "Invalid parameter 'provider'!"
class: "InvalidParameters"
timestamp: "2019-04-24T19:39:49.165Z"
Error: Your request parameters did not validate. 'provider': Invalid parameter 'provider'! at AuthService.<anonymous> (/opt/realm/node_modules/realm-object-server/dist/services/AuthService.js:328:23) at Generator.next (<anonymous>) at /opt/realm/node_modules/realm-object-server/dist/services/AuthService.js:19:71 at new WrappedPromise (/home/realm/.nvm/versions/node/v10.15.3/lib/node_modules/pm2/node_modules/async-listener/es6-wrapped-promise.js:13:18) at __awaiter (/opt/realm/node_modules/realm-object-server/dist/services/AuthService.js:15:12) at AuthService.authenticate (/opt/realm/node_modules/realm-object-server/dist/services/AuthService.js:295:16) at BasicServer.<anonymous> (/opt/realm/node_modules/realm-object-server/dist/Server.js:546:77) at Generator.next (<anonymous>) at /opt/realm/node_modules/realm-object-server/dist/Server.js:7:71 at new WrappedPromise (/home/realm/.nvm/versions/node/v10.15.3/lib/node_modules/pm2/node_modules/async-listener/es6-wrapped-promise.js:13:18)
10.100.166.62 - POST /auth HTTP/1.1 400 234 - 0.727 ms
</pre>
</details>

What is the correct way to create the payload?

**Comment by nirinchev** [comment]
Did you set the name property on the server provider implementation to `crm`?

**Comment by pierre-moire** [comment]
Yes, but I made a mistake in the provider code as I used a JS only version (no Typescript)

Sorry, my bad!
