### ISSUE TITLE
Realm Studio can't be opened on Mac

### ISSUE THREAD

**Issue by j3n** [realm/realm-object-server#431]
## Goals

Open Ream Studio on Mac

## Expected Results

Realm Studio opened

## Actual Results

Apple prevent from opening
Error message in french : Impossible d’ouvrir « Realm Studio », car Apple ne peut pas vérifier qu’il ne contient pas de logiciels malveillants.
Ce logiciel doit être mis à jour. Contactez le développeur pour en savoir plus.

## Steps to Reproduce

Install Realm Studio on Mac and try to open

## Version of Realm and Tooling

RealmStudio 3.8.3
Mac OS Catalina 10.15.1

**Comment by nirinchev** [comment]
Duplicate of https://github.com/realm/realm-studio/issues/1139.
