### ISSUE TITLE
Install on Debian

### ISSUE THREAD

**Issue by leolelego** [realm/realm-object-server#45]
Hi,

I follow ubuntu instruction to install on my debian, I get this error : 
`E: Unable to locate package realm-object-server-de`

Do you just not support debian at all ?

config : 
debian 8.5
x86_64 GNU/Linux

thanks 😊

**Comment by teotwaki** [comment]
Hi @leoderbois,

This is correct, we only support Ubuntu, CentOS/RHEL 6 and 7 at the moment. As indicated in another issue, we've decided to prioritise feature development rather than packaging. Debian is a fairly often requested distribution though.
