### ISSUE TITLE
Support Realm Object Server on windows platform.

### ISSUE THREAD

**Issue by HMMakadiya** [realm/realm-object-server#46]

**Comment by VagueGit** [comment]
The docs for ROS 2.0 [Install Realm Object Server](Install Realm Object Server) says 

> Windows: coming soon!

Where is ROS on Windows on the roadmap?

**Comment by judsonabraham301** [comment]
Can we run ROS in windows using Docker?

**Comment by nirinchev** [comment]
Yes, you can run it in docker.

**Comment by nirinchev** [comment]
You can check the docs for installing ROS here: https://docs.realm.io/platform/self-hosted/installation/installing-via-docker
