### ISSUE TITLE
nodejs 4.2.6 dependency on Ubuntu

### ISSUE THREAD

**Issue by Jerrot** [realm/realm-object-server#53]
After some updates on my Ubuntu 16.04 machine, the realm-object-server-de upgrade fails for me due to the dependency on some older nodejs version:

```
The following packages have unmet dependencies:
 realm-object-server-de : Depends: nodejs (= 4.2.6~dfsg-1ubuntu4.1) but 4.6.2-1nodesource1~xenial1 is to be installed
```

Any resolution but downgrading nodejs?

**Comment by teotwaki** [comment]
@Jerrot Are you using only packages provided from the official repos, or did you install a newer version of node from some other source?

**Comment by Jerrot** [comment]
@teotwaki Hmm, ok, I found some external apt-source which includes the line
`"deb https://deb.nodesource.com/node_4.x xenial main"`
I guess that one updated node, however I'm not experienced enough to understand why it is there and if I need it. So downgrade is my only hope to get realm object server running?

**Comment by teotwaki** [comment]
@Jerrot We're working on being more lenient with regards to Node versions in the future, and also hope to provide Docker images and whatnot to make it less conflicting with whatever else people might have on their system. In the mean time, I'm afraid so.

**Comment by nonameolsson** [comment]
I'll hijack this thread..  I get the same message. I have Ubuntu 16.04 with Node `v4.6.2` installed.

```
andreas@ubuntu-512mb-lon1-01:~$ node -v
v4.2.6
andreas@ubuntu-512mb-lon1-01:~$ sudo apt-get install realm-object-server-developer
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 realm-object-server-developer : Depends: nodejs (= 4.2.6~dfsg-1ubuntu4.1) but 6.9.2-1nodesource1~xenial1 is to be installed
E: Unable to correct problems, you have held broken packages.
andreas@ubuntu-512mb-lon1-01:~$
```

What could be the problem now?

**Comment by danielmhanover** [comment]
+1

**Comment by nnrealm** [comment]
Re: node versions, I'm far from an expert, but there's some issues with one of our dependencies (node-pre-gyp) which causes breakage on Debian-based installs. (Although different to this?)

As far as I could tell, the quickest, if not prettiest, way to get a functional install on an Ubuntu machine is to use Node packages from Nodesource here: https://github.com/nodesource/distributions#deb

I've not tried with 4.2.6, though, just recentest LTS.

**Comment by bigfish24** [comment]
Closing as this pertained to ROS 1.x and 2.0 has a different installation with NPM.
