### ISSUE TITLE
Realm-tasks logout does not prevent auto-login on next run

### ISSUE THREAD

**Issue by dsjstc** [realm/realm-object-server#68]
The SignInActivity in the realm-tasks example always logs in as SyncUser.currentUser(), unless it is launched with an intent of ACTION_IGNORE_CURRENT_USER.  That means that if you log out and destroy the application (reboot hardware, manual terminate, etc), the next run of the application will autologin *as the last logged-in user*.

I did not immediately see any trivial way to invalidate the stored login credentials at logout -- this might be a bug in the underlying authentication mechanism.

Expected behaviour: logout is sticky across restarts.

**Comment by bigfish24** [comment]
@dsjstc thanks for reporting this. @dalinaum or @austinzheng do you have any thoughts? We should probably move this issue to either https://github.com/realm/RealmTasks or https://github.com/realm/realm-object-store depending on where we think the issue is.

**Comment by dalinaum** [comment]
Thanks @dsjstc 

Although I don't know it's an issue of `SignInActivity` or other parts yet, I should look into `SignInActivity` first and create this issue to RealmTasks or other repositories later.

**Comment by dalinaum** [comment]
I tested Realm Java version 2.2.1 and Realm Java version 2.3.0-SNAPSHOT. Although version 2.2.1 have a problem, it works well on version 2.3.0. I will update RealmTasks later.

I modified the following files:
