### ISSUE TITLE
Feature Request: Tresorit ZeroKit (OpenID) Provider Support

### ISSUE THREAD

**Issue by RiverbayChris** [realm/realm-object-server#96]
Tresorit and Apple just partnered on ZeroKit integration for CareKit.  Zerokit handles secure auth as well as data encryption, but not the actual storage of it.  This would be a great compliment to the ROS if it could be added as a provider.  I think it is based on OpenID, so maybe solving that one would solve many other integrations.

Those developing professional healthcare apps (like me) could really use this in addition to ROS.

https://tresorit.com/zerokit/carekit

**Comment by radu-tutueanu** [comment]
Thank you for the suggestion, @TotemChris . The server does allow people to implement integrating with third party authentication providers, we will be documenting this api soon. 
We are always looking to include the security that the apps that use us require.

**Comment by davidszabo26** [comment]
Hi @radu-tutueanu, this is David from the ZeroKit team. @TotemChris reached out to us and asked to integrate our secure user authentication with Realm, so that they can use Realm in healthcare. We'd be very happy to do this piece of work, how can we collaborate?

**Comment by bigfish24** [comment]
An initial integration was done mid 2017: https://realm.io/blog/end-to-end-encryption-for-realm-by-tresorit-zerokit/
